### ISSUE TITLE
Software Store constantly crashing after switch to linux-surface kernel in Zorin OS

### ISSUE THREAD

**Issue by erik-lindner** [linux-surface/linux-surface#1526] opened 2024-08-10 08:55 UTC
Hi

my issue is that after I switched to the surface kernel the Software Store of the Zorin OS keeps constantly crashing.
I have already tried these fixes: https://forum.zorin.com/t/fixing-the-common-problems-of-software-center/22945
But for most installation commands I then get the error "Method https has died unexpectedly!".

I now switched back to the previous kernel ( Linux 6.5.0-45-generic ) and now the software store is working properly again.

Does anyone perhaps know a solution to this nifty problem?
Because I do not want to constantly switch to the old kernel if I want to install a software. Because now it seems that with the surface kernel I cannot install apps via the Software Store nor via the command line.
I really want to have the touchscreen running on my Surface Pro 4.

Hopefully someone has a quick solution to this problem. 
Thanks in advance.

Oh and one further note:
During the installation process of the surface kernel I ran into the issue that the kernel could not be loaded properly.
I got the message during the startup: "Bad Shim-Signature. You have to load the kernel first.".
After trial and error and a long search I found out that I have to completely disable the secure boot setting in the boot menu. After that the Zorin OS worked with the surface kernel. The touchscreen worked then but I unfortunately I then ran into the above issues.
Maybe you could include that as a not in the installation guide. It was really nervewracking.

### Environment

- Hardware model: Surface Pro 4
- Kernel version: Previous kernel = Linux 6.5.0-45-generic || Surface kernel = Linux 6.10.3-surface-1
- Distribution: Zorin OS

**Comment by qzed** [comment] 2024-08-16 10:31
I assume this has the same root cause as #1534, so I'll close it for now. Can you check if you can spot `trap invalid opcode` in the kernel log? If not, please let me know and we can re-open this issue.

**Closed by qzed** 2024-08-16 10:31 UTC
