### ISSUE TITLE
System does not start with latest patched kernel

### ISSUE THREAD

**Issue by lamyseba** [linux-surface/linux-surface#1095] opened 2023-03-15 17:39 UTC
Hi, I'm running manjaro-linux on a surface 3. When I upated to latest linux-surface kernel (6.2.5), my system could not start. Sorry I'm quite unexperienced with bug-reports and bug investigating, so I have no "command line results" to write.

System fail to start and I could not identify a decisive error message. It just stays stucked before lauching desktop manager (xfce) or while launching it (dark screen). I cannot access to anything even a command line tool.

With the latest unpatched LTS kernel available in manjaro (6.2.1.12-1), The system starts OK. I did not try with 6.2.0rc8-1, because it's labelled as "experimental". 

I don't know if there is any annoyance with the kernel that is not surface-patched. At least hibernation does not work, but I'm not sure it would work with the surface-patched version. Some times ago, power down management was bad in unpatched kernel, and my surface 3 was still consuming battery after a power-down, So battery went empty if not plugged. Will investigate if this is still the case.

**Comment by maxso-216** [comment] 2023-03-16 06:45
I also have the same issue.
I am using arch linux, after updating the kernel to latest (6.2.5), it won't boot.
I try to downgrade the kernel with arch linux install iso, the install media also stop booting.
Interestingly, the install media throws errors about atomisp before hanging.
I manage to downgrade the kernel by using an older arch linux install iso.
So I think the error is relate to some mainstream kernel change related to atomisp.

**Comment by lamyseba** [comment] 2023-03-16 09:41
I've got a message error also about atomisp, but the boot can get a little bit further. Searching the net I found that atomisp is related to camera, wich doesnt't work since a while on linux OS, so I thought this was not the source of the problem.

If the unpatched version (from install iso) has the same problem, then there is twoo solution we should explore.
1. Report the bug to the kernel team (don't know the right place to do this, any help welcome)
2. Have the linux-surface patched version fix that bug (I don't know if this solution is possible)

**Comment by maxso-216** [comment] 2023-03-16 11:24
Those are possible solutions, but I must say report to kernel team is the best (?)
I am not a programmer, so I could only do very basic logging and report bug on related website.
I have no idea which log to report or what caused the system won't boot. At least what I know is the current unpatched kernel is not working. (by using latest arch linux install media)
Maybe someome here experienced can help.

**Comment by qzed** [comment] 2023-03-16 11:41
Can you check if https://github.com/linux-surface/linux-surface/releases/tag/arch-6.2.2-2 still works?

**Comment by qzed** [comment] 2023-03-16 13:11
Sorry, can you clarify again which version did work? I assume the above is a typo and you meant 6.1.12-1 (not some 6.2.x-y?). Does Manjaro's 6.2 kernels work (I think 6.2.6-1 should be the current one)?

**Comment by lamyseba** [comment] 2023-03-16 14:06
@qzed, 6.2.1.12-1 does indeed work (at least the "normal manjaro" version, wich I'm using at this very moment), but the above was not a typo, you gave a link asking to try 6.2.2-2 => I tried it and it was also failing to start.

**Comment by lamyseba** [comment] 2023-03-16 14:51
I tried to launch with loglevel=7. Failing at startup is not always the same, but i'm pretty sure it occurs shortly after error messages about atomisp. At the time of failing, system is totally freezed, I cannot access a console with ctrl+alt+F2 or ctrl+alt+F3. Nothing is responding anymore and screen output is also freezed "as is" when system fail.

In my startup config, system prints messages while starting (the ones you can normally see when hitting ctrl+alt+F1 when system is already started in a desktop environment).  I had no "quiet" option. This is the kind of errors I got trying various times to start system with the newer kernel.
* Sometimes I got a message saying that one of my CPU is stuck and system try to stop wainting for him. Then system is freezed. This message occurs shortly after messages complaining about atomisp.
* Sometimes it fails just while lauching the desktop environement. This means printing of startup log messages seems to be all done, and then the screen goes black because Desktop environment is launching. In a normal boot, after one or twoo seconds, I get the desktop environment displaying. But with problematic Kernel I stay stucked in the black screen, Desktop never show. It seems there is no backlight, but not sure about this point. Because log messages are addeds very quickly before screen goes black for launching Desktop environement, I cannot read anything that was written before dark screen.
* This time it get stuck with a message :

> mmc0:  Timeout waiting for hardware interrupt. 

Just before I had some message about atomisp, I noted part of them :

> atomisp-isp2: atomisp: Error -2 while requesting firmware shisp_2401a0_v21.bin
> atomisp-isp2 : IUNIT poweroff timeout
> atomisp-isp2 : Failed to switch off ISP

It seems the Error requesting firmware occurs also in a successfull startup with older kernel, I can see it when typing a `dmesg` command after a successfull boot with old kernel.

It is difficult to report fail log, as I have to copy it manually from the frozen screen and type it here afterwards. Is there a command like dmesg wich could show me the boot log messages, even afterwards, for the failed boots ?

Side note: dmesg prints warning about Kernel being a DEBUG Kernel. This is not new and unrelated to this bug, but why do we have this message ?

```
**********************************************************
[    6.801165] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
[    6.801167] **                                                      **
[    6.801168] ** trace_printk() being used. Allocating extra memory.  **
[    6.801169] **                                                      **
[    6.801171] ** This means that this is a DEBUG kernel and it is     **
[    6.801172] ** unsafe for production use.                           **
[    6.801173] **                                                      **
[    6.801174] ** If you see this message and you are not debugging    **
[    6.801176] ** the kernel, report this immediately to your vendor!  **
[    6.801177] **                                                      **
[    6.801178] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
[    6.801179] **********************************************************
```

**Comment by qzed** [comment] 2023-03-16 14:52
What is  `6.2.1.12-1` for a version specifically, as in upstream kernel version? Upstream kernels follow the `x.y.z` scheme, kernel packages generally `x.y.z-r`, Manjaro included (see e.g. https://software.manjaro.org/package/linux62, which is currently at `6.2.6-1`).

So I can't really make sense of that version, sorry.

**Comment by qzed** [comment] 2023-03-16 15:01
You can try `journalctl -b -1` which gives you the log of the last boot (replace `-1` with some other negative number if you want to go further back). That may or may not work depending on whether systemd saved the log before the crash.

> ```
> atomisp-isp2: atomisp: Error -2 while requesting firmware shisp_2401a0_v21.bin
> ```
This just means it can't find the firmware (error -2 is "No such file or directory") and should be completely fine. The driver should abort and just not load.

>  Side note: dmesg prints warning about Kernel being a DEBUG Kernel. This is not new and unrelated to this bug, but why do we have this message ?

Is that on the Surface kernel or the Manjaro one?

**Comment by qzed** [comment] 2023-03-16 15:08
Ah, for the message see https://github.com/linux-surface/linux-surface/issues/451. It likely comes from `atomisp` being still a work-in-progress thing. We've disabled it on Ubuntu/Debian, we could disable it on Arch as well.

On that note, can you try to blacklist `atomisp` and check if that makes a difference?

**Comment by lamyseba** [comment] 2023-03-16 17:38
blacklisting atomisp made the boot succeed.

Don't know if this has to do with our problem, but I found that on [an email list about kernel](https://lore.kernel.org/lkml/20211101141058.36ea2c8e@sal.lan/T/):

>So the drivers for e.g. the ov5693 sensor conflict, by adding
a small (one line) check to atomisp_ov5693.c to not register
the driver at all when not on BYT/CHT we can avoid the conflict
on most devices for now. And when actually on BYT/CHT the user
will need to blacklist the non atomisp sensor-modules which, well
sucks, but atomisp is in staging for a reason ...
>
> So the idea here is that with some small added ugliness to the
atomisp_foo.c sensor drivers we can make the 2 drivers co-exist
a bit more, allowing e.g. generic distro kernels to (maybe) enable
the atomisp2 stuff without regressing the IPU3 support.

**Comment by maxso-216** [comment] 2023-03-17 03:15
Out topic, but using latest  (or since 5.18) patch driver have cause the touchscreen driver  to crash randomly. Do you experience similar problem?

**Comment by qzed** [comment] 2023-03-17 12:51
> blacklisting atomisp made the boot succeed. smile

Great, thanks! I'll disable atomisp and related modules in our kernels for now. I don't believe that they currently work on any of the devices we support, so if it breaks one that's probably the best workaround for now.

**Comment by lamyseba** [comment] 2023-03-17 13:33
Workaround for now: ok, but we should not overlook to report the bug upstream.

But what is upstream ? linux Kernel team (wich part?) ? atomisp module team ? Both ?

**Comment by qzed** [comment] 2023-03-17 13:49
The MAINTAINERS file should have that info. But we can maybe try and figure out a bit more before we report it in. Can you try to load the module at runtime (after booting with it blacklisted)? And can you post the config of the Manjaro kernel? I think it should have that enabled as well, so maybe it's a clash with something in our kernel.

**Comment by pau-a-velo** [comment] 2023-03-17 17:20
Load module at runtime : lauching in console

     sudo modeprobe atomisp

This freeze my system, cant do nothing, have to reboot.

> can you post the config of the Manjaro kernel?

Not sure about how to get this info. Looking on the net, I found this command, wich I run after a boot with unpatched manjaro kernel `6.1.19-1` and that ouput attached file

    zcat /proc/config.gz > manjaro_kernel-6.1.19-1_config.txt

[manjaro_kernel-6.1.19-1_config.txt](https://github.com/linux-surface/linux-surface/files/11004025/manjaro_kernel-6.1.19-1_config.txt)

**Comment by qzed** [comment] 2023-03-17 17:51
Thanks! So this definitely has atomisp enabled. Can you check if the v6.2 kernel provided by Manjaro (https://software.manjaro.org/package/linux62) has the same issue as ours or whether it works? And if it works, can you also grab a config for that?

**Comment by lamyseba** [comment] 2023-03-17 17:51
Load module at runtime : lauching in console

     sudo modprobe atomisp

This freeze my system, cant do nothing, have to reboot.

> can you post the config of the Manjaro kernel?

Not sure about how to get this info. Looking on the net, I found this command, wich I run after a boot with unpatched manjaro kernel `6.1.19-1` and that ouput attached file

    zcat /proc/config.gz > manjaro_kernel-6.1.19-1_config.txt

[manjaro_kernel-6.1.19-1_config.txt](https://github.com/linux-surface/linux-surface/files/11004025/manjaro_kernel-6.1.19-1_config.txt)

**Comment by qzed** [comment] 2023-03-17 18:37
> Load module at runtime : lauching in console
> 
> ```
>  sudo modprobe atomisp
> ```
> 
> This freeze my system, cant do nothing, have to reboot.

Can you also run `dmesg -w` at the side in another console and see if that output something before the freeze?

**Comment by maxso-216** [comment] 2023-03-18 08:38
[DSC_0004](https://user-images.githubusercontent.com/107261566/226094859-f16471a6-78ee-4f2a-aea4-18c4bb6ce3d4.JPG)

This is the message I get before hang
Running under linux-surface 6.2.5-1

**Comment by qzed** [comment] 2023-03-18 12:42
Okay, so at this point we really need to know if this happens with an unpatched v6.2 kernel as well. I suspect it does since we don't touch anything related to that, but we should check to make sure.

Another thing you should check: It could be related to the missing firmware. Can you download [this file](https://github.com/intel-aero/meta-intel-aero-base/blob/master/recipes-kernel/linux/linux-yocto/shisp_2401a0_v21.bin) and copy it to `/lib/firmware/shisp_2401a0_v21.bin`? Then load the module again and check if that makes a difference.

**Comment by maxso-216** [comment] 2023-03-18 16:07
[DSC_0005](https://user-images.githubusercontent.com/107261566/226117173-16b62f63-b0c3-4958-81d1-7bdf89d6bd62.JPG)
This is under unpatched kernel. Same result.
[DSC_0006](https://user-images.githubusercontent.com/107261566/226117195-c327407b-6254-4bfd-8813-801ee2169129.JPG)
This is after shisp_2401a0_v21.bin is added. Using linux-surface 6.2.5-1. System does not crash or hang, can continue operation.

**Comment by qzed** [comment] 2023-03-18 16:16
Thanks! So it seems that the missing firmware causes issues.

@jwrdegoede, it looks like most atomisp changes between v6.1 and v6.2.6 come from you. Any ideas what could cause this problem?

**Comment by Lumipyry** [comment] 2023-04-23 21:04
@qzed 
Thank You for this info.
Newly released Ubuntu 23.04 and Kubuntu 23.04 use Kernel 6.2.0-20 and a computer with Intel Atom CPU  (HP x2 210 G 2) WON'T BOOT with that kernel.
Your info helped to figure out what is the problem. I just filed a bug report in Ubuntu bug tracking system (" https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2017444 ") concerning this problem. The last stable Ubuntu kernel that an Intel Atom CPU computer boots with is 6.1.25.

Interestingly in both Ubuntu Kernels 5.19.0-40 (used in previous Ubuntu 22.10) and 6.1.25 the dmesg.log tells that atomisp failes to launch but still the computer boots.

**Comment by qzed** [comment] 2023-04-23 23:07
@Lumipyry Thanks! It's helpful to know that Surface devices aren't the only ones being affected. And thanks for bringing this up with Ubuntu. I think ultimately, this should be probably reported to the atomisp kernel devs, but bringing this up with Ubuntu maintainers is probably a good start for that.

**Comment by Lumipyry** [comment] 2023-04-23 23:53
I just tested Ubuntu Kernel 6.3.0 - No success - atomisp failure.

**Comment by Lumipyry** [comment] 2023-04-28 20:52
@qzed
Downloading shisp_2401a0_v21.bin from https://github.com/intel-aero/meta-intel-aero-base/blob/master/recipes-kernel/linux/linux-yocto/shisp_2401a0_v21.bin and copying it to /lib/firmware makes Ubuntu kernels 6.2 and 6.3 bootable with Intel Atom.
 I just wrote a bittersweet message to Intel in their processor forum https://community.intel.com/t5/Processors/Answer-to-Intel-regarding-Intel-Atom-CPU-computers-failing-to/m-p/1481415#M62853 .

**Comment by StollD** [comment] 2023-04-28 21:00
I am normally the first one to blame Intel, but in this case the blame lies on Ubuntu. The atomisp driver is under `drivers/staging`, which explicitly contains drivers that are not production ready. Its the codified "hmm, better than nothing".

If Ubuntu enables a driver from staging, they have to make sure that it works.

**Comment by Lumipyry** [comment] 2023-04-28 21:22
I just found mailing list of Intel atomisp linux developers (working for Intel). One of them is my fellow countryman (finnish). Maybe i'll just ask him. 
Intel's Linux development may be situated in Tampere, Finland, and it's only 100 km from my home. Maybe i'll visit them personally. If I do - do you have any messages for them?

**Comment by qzed** [comment] 2023-04-28 21:39
Keep in mind: The devs themselves (very likely) have little to no say in what part of their hardware Intel supports for Linux, so please don't blame them.

What I'd love to see is to either have corporations (not just Intel) decide to support something and stick to that or decide not to support it but then at least make necessary documentation available to people willing to contribute to the kernel. So, ideally, we wouldn't need to rely on hardware vendors for software. But that's a whole other debate... and that's probably also never going to happen...

On the subject of who's to blame for this: I don't think it's that black-and-white. Generally, the maintainers should ensure that everything is running, but depending on hardware availability (and whether they actually work for some company or do maintain that driver in their free time / on the side), that's not always easy. And given that it is in staging, it might very well be that it's a side-project of someone trying to polish up some Intel code-dump... Which as @StollD said also puts some responsibility on distros enabling those modules. The config option explicitly states that:

>  Please note that these drivers are under heavy development, may or may not work, and may contain userspace interfaces that most likely will be changed in the near future.

Of course there's a bit of a difference (IMHO) between not working and breaking the system though...

**Comment by qzed** [comment] 2023-04-28 21:41
> Could You consider informing atomisp kernel devs, since you are an expert.

Sorry, just saw this. I would prefer if you write them as I don't have an affected device. So I can really just point them here and/or repeat what's being discussed here.

I understand you've found the mailing-list in question? You could also look at the commit history or use the `./scripts/get_maintainers.pl` script to find people to write.

**Comment by Lumipyry** [comment] 2023-04-28 22:00
@qzed
Some of the persons in list work for Intel, some for Red Hat and kernel.org  - and I would never even dream of blaming them for anything. I could only pollitely ask for information (from my countryman). And I'm only half serious here. By atomisp kernel devs - do you mean these persons?  Sorry, don't understand anything you white about commit history, I'm just a basic user - not programmer.

**Comment by Lumipyry** [comment] 2023-04-28 22:02
@StollD 
I can't find `drivers/staging` in Kubuntu

**Comment by Lumipyry** [comment] 2023-04-28 22:11
What I planned to perhaps do - is ask my coutryman that is he aware, that none of the linux distributions boot with kernel 6.2

**Comment by qzed** [comment] 2023-04-28 22:20
> By atomisp kernel devs - do you mean these persons?

Yes. You can look at the commit history e.g. at https://github.com/torvalds/linux/commits/master/drivers/staging/media/atomisp. Each of the commit messages have some tags with mails (`Reviewed-by`, ` Signed-off-by`). The last `Signed-off-by` is usually by the tree maintainer, which might not have all that much to do with the code itself (but they should be able to point you at the persons to contact).

With the script I meant that you can run
```
./scripts/get_maintainer.pl drivers/staging/media/atomisp
```
Which will give the following output:
```
Hans de Goede <hdegoede@redhat.com> (maintainer:STAGING - ATOMISP DRIVER)
Mauro Carvalho Chehab <mchehab@kernel.org> (maintainer:STAGING - ATOMISP DRIVER)
Sakari Ailus <sakari.ailus@linux.intel.com> (reviewer:STAGING - ATOMISP DRIVER)
Greg Kroah-Hartman <gregkh@linuxfoundation.org> (supporter:STAGING SUBSYSTEM)
linux-media@vger.kernel.org (open list:STAGING - ATOMISP DRIVER)
linux-staging@lists.linux.dev (open list:STAGING SUBSYSTEM)
linux-kernel@vger.kernel.org (open list)
```
So the first two or three are probably the ones you want to contact, with the `linux-media` mailing-list in CC. Maybe also `Andy Shevchenko <andy.shevchenko@gmail.com>` who reviewed some of the latest commits (and I believe at some point worked for Intel). There's also [bugzilla.kernel.org](https://bugzilla.kernel.org/) but I think it depends on the subsystem as to what's the preferred way to report bugs.

**Comment by Lumipyry** [comment] 2023-04-28 22:42
Sakari Ailus is the fellow countryman I was referring. Is it wise to give the list in public? Should you delete your answer? I fear they will get a lot of spam messages

**Comment by qzed** [comment] 2023-04-28 23:42
Regarding concerns about public mails: It's all from the [MAINTAINERS](https://github.com/torvalds/linux/blob/master/MAINTAINERS) file, so I think it shouldn't really be a concern (also: mine is in there as well and the gmail spam filter is surprisingly effective, but given the "quality" of most of those mails, I'm not sure if I should be surprised...).

**Comment by jwrdegoede** [comment] 2023-04-29 09:22
Hi All,

Upstream maintainer / person trying to get it into working shape for the atomisp driver.

The atomisp driver crashing the entire system when the firmware is missing is a known issue / recent regression, which is pretty high on my list of things to fix.

With that said, this driver is nowhere near ready for general use, which is why it is in drivers/staging, so it should really not be enabled!

Assuming this driver being enabled is part of the upstream Ubuntu kernels, please file a bug with Ubuntu to have this driver disabled for now. Enabling this driver for anyone who is not actively working on developing the driver is not doing anyone any favors for now.

Regards,

Hans

**Comment by Lumipyry** [comment] 2023-04-29 14:48
@jwrdegoede 

Disabling driver is not an option (in Ubuntu kernel) , since it's already missing. What Ubuntu kernel maintainers should do - is to disable atomisp modules. The maintainers are not aware of this problem - so could You or someone from your group please inform them.

**Comment by qzed** [comment] 2023-04-29 15:52
> What Ubuntu kernel maintainers should do - is to disable atomisp modules.

I believe this is what @jwrdegoede meant.

> The Ubuntu kernel maintainers are not aware of this problem - so could You or someone from your group please inform them.

There is the bug report you opened (https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2017444), so you should probably ask them to disable the modules there.

But given the severity, it would probably be good if we could contact someone more directly and make them aware of that to speed things up a bit (especially considering that there's a fairly simple "fix"). Unfortunately, I don't know any of the maintainers or who to contact here. Ubuntu essentially links to launchpad and a malinig list (see links on [this page](https://packages.ubuntu.com/lunar/linux-image-generic)).

**Comment by Lumipyry** [comment] 2023-04-29 16:00
The Bug report is mine.

But there are so many bugs reported in Ubuntu, that it may possible that no-one ever reads this. 

I try to "advertise" this bug in AskUbuntu question https://askubuntu.com/questions/1464926/not-able-to-boot-kubuntu-23-04-with-kernel-6-2-and-intel-atom-cpu but....

**Comment by Lumipyry** [comment] 2023-04-29 16:31
@qzed 
Thank you for your answer. One question here - not so important - don't have to answer.

To get consepts right:
Is shisp_2401a0_v21.bin called driver or file?
or
is the whole set of modules called atomisp driver?

**Comment by StollD** [comment] 2023-04-29 16:43
shisp_2401a0_v21.bin is firmware. Firmware runs on the device, while the driver runs on the main CPU and interacts with the firmware running on the device.

On linux, drivers can be either built into the main kernel binary, or into loadable modules. So you often see modules and drivers being used to describe the same thing.

**Comment by qzed** [comment] 2023-04-29 16:50
I think you can break things down into (mostly) three concepts here:

- _Firmware_, which for our purposes is generally anything that's loaded by a driver. Often, this is firmware loaded onto the device. However: From the kernel/packaging perspective, that can also include some driver configuration database files that aren't really loaded onto the device but used in the driver itself instead. So the definition is often broader than the "classical" term "firmware".

  So the `shisp_2401a0_v21.bin` would be considered firmware.

- _Modules_ are loadable code-units. You can essentially think of this as a shared library (.so on Linux, .dll on Windows) for the kernel. Generally, they can also be built into the kernel, but the key point is that they're essentially loadable libraries, containing some code.

  That doesn't necessarily mean that a module must always contain a driver, but it could also contain some helper functions for drivers. For example, the Surface HID drivers are structured into 3 modules: A module for the legacy driver, a module for the "new" driver, and a common module that does not contain any drivers, but contains helper functions used by both driver modules. Here, this helps reduce some code duplication, meaning we don't need to statically link the helper functions into both driver modules.

- _Drivers_ are, well... drivers managing the hardware. This is more about the code / structure of the code than how it's being loaded (so essentially drivers and modules are somewhat orthogonal concepts). Drivers are generally written as modules, so that a system can load only those drivers it needs, but in some rarer circumstances that doesn't work.

**Comment by Lumipyry** [comment] 2023-04-29 17:05
May I also ask an unrelated question. I'm finnish and I studied a bit of german in school. At that time I was taught that it's unpollite in Germany to call a stranger by first name. How is nowadays - should I say Mr Lutz, or Maximilian? In Finland we call everyone by first name, with only one exception - The President of Finland is usually called Mr or Ms.

**Comment by qzed** [comment] 2023-04-29 17:12
Personally, feel free to call me Max. I think first name is pretty much standard for kernel development and I much prefer that here on GitHub as well. As for Germany in general: It's a bit more varied and depends on the setting. I guess in somewhat formal settings with strangers we're still pretty conservative, using the last name.

**Comment by Lumipyry** [comment] 2023-04-29 17:22
asking because earlier I sent Hans de Goede email which started "Hans".  - Mr de Goede - I hope I didn't affend You and I'm sorry if I did.

**Comment by jwrdegoede** [comment] 2023-04-29 17:30
> What Ubuntu kernel maintainers should do - is to disable atomisp modules.

Right, that is what I said / meant.

> The Ubuntu kernel maintainers are not aware of this problem - so could You @jwrdegoede , or someone else from atomisp kernel developers please inform them.

I have a couple of contacts at Ubuntu I have just send them an email about this.

> asking because earlier I sent Hans de Goede email which started "Hans". - Mr de Goede - I hope I didn't affend You and I'm sorry if I did.

No worries as @qzed said kernel devs usually use first names anyways. Also I'm Dutch and we generally are somewhat less formal here.

**Comment by qzed** [comment] 2023-04-29 17:37
@jwrdegoede Thank you!

**Comment by Lumipyry** [comment] 2023-04-29 18:00
@jwrdegoede 
Thank You!
I have one more favor to ask.  Could you - just to make sure - please write a comment in my Bug Report https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2017444 so the Ubuntu kernel maintainers believe me better.

**Comment by Lumipyry** [comment] 2023-04-29 18:09
@jwrdegoede 
Thank You!

**Comment by Lumipyry** [comment] 2023-05-01 09:19
@qzed 
Sorry to bother you again. The atomisp modules, can you confirm that this list upto date:
atomisp
atomisp-gc0310
atomisp-gc2235
atomisp-libmsrlisthelper
atomisp-lm3554
atomisp-mt9m114
atomisp-ov2680
atomisp-ov2722
atomisp-ov5693

or is there more / less. 
I think it's best to add this list to bug report.  The bug has been assigned to a Canonical worker.

**Comment by jwrdegoede** [comment] 2023-05-01 09:23
Quick update on this, I've gotten confirmation from a Ubuntu kernel engineer that they are working on fixing this (by disabling atomisp support).

**Comment by juergh** [comment] 2023-05-02 20:06
Ubuntu linux-firmware and kernel maintainer here. Yes, we're aware of the problem. For the record, you can always reach us on libera.chat IRC #ubuntu-kernel.

**Comment by qzed** [comment] 2023-05-02 20:34
@juergh Thanks! That's good to know.

**Comment by qzed** [comment] 2023-05-08 22:08
I believe we can close this issue then. We've disabled `atomisp` in [777db9f](https://github.com/linux-surface/linux-surface/commit/777db9f98eb888d2fe05736db4ce74255546483b) on our end and the respective maintainers are aware of the issue.

If you encounter this issue on another distribution, please inform the respective maintainers of that distro.

**Closed by qzed** 2023-05-08 22:08 UTC
