### ISSUE TITLE
SP 4, Debian 12 Bookworm, LK 6.7.2-surface-1, No working cameras, all cameras are being detected, but not initialised

### ISSUE THREAD

**Issue by WizardNumberNext** [linux-surface/linux-surface#1361] opened 2024-02-04 12:19 UTC
Hardware model: Surface Pro 4
Kernel Version: 6.7.2-surface-1
Distribution: Debian 12 Bookworm with libcamera compiled to instructions provided here

I have removed portions of dmesg not related to cameras, video4linux, media

```
[   33.333181] mc: Linux media interface: v0.10
[   33.382998] videodev: Linux video capture interface: v2.00
[   33.586348] ov8865 i2c-INT347A:00: supply dvdd not found, using dummy regulator
[   33.586404] ov8865 i2c-INT347A:00: supply dovdd not found, using dummy regulator
[   33.586417] ov8865 i2c-INT347A:00: supply avdd not found, using dummy regulator
[   33.587941] ov8865 i2c-INT347A:00: supply dvdd not found, using dummy regulator
[   33.587981] ov8865 i2c-INT347A:00: supply dovdd not found, using dummy regulator
[   33.587992] ov8865 i2c-INT347A:00: supply avdd not found, using dummy regulator
[   33.599026] ov8865 i2c-INT347A:00: supply dvdd not found, using dummy regulator
[   33.599071] ov8865 i2c-INT347A:00: supply dovdd not found, using dummy regulator
[   33.599081] ov8865 i2c-INT347A:00: supply avdd not found, using dummy regulator
[   33.655215] ov8865 i2c-INT347A:00: supply dvdd not found, using dummy regulator
[   33.655245] ov8865 i2c-INT347A:00: supply dovdd not found, using dummy regulator
[   33.655253] ov8865 i2c-INT347A:00: supply avdd not found, using dummy regulator
[   33.720142] ov8865 i2c-INT347A:00: supply dvdd not found, using dummy regulator
[   33.720186] ov8865 i2c-INT347A:00: supply dovdd not found, using dummy regulator
[   33.720197] ov8865 i2c-INT347A:00: supply avdd not found, using dummy regulator
[   33.757546] ov8865 i2c-INT347A:00: supply dvdd not found, using dummy regulator
[   33.757700] ov8865 i2c-INT347A:00: supply dovdd not found, using dummy regulator
[   33.758560] ov8865 i2c-INT347A:00: supply avdd not found, using dummy regulator
[   33.760848] ipu3_imgu: module is from the staging directory, the quality is unknown, you have been warned.
[   33.762866] ipu3-imgu 0000:00:05.0: enabling device (0000 -> 0002)
[   33.763079] ipu3-imgu 0000:00:05.0: device 0x1919 (rev: 0x1)
[   33.763101] ipu3-imgu 0000:00:05.0: physical base address 0x00000000a1000000, 4194304 bytes
[   33.805931] ipu3-cio2 0000:00:14.3: Found supported sensor INT33BE:00
[   33.806106] ipu3-cio2 0000:00:14.3: Found supported sensor INT347A:00
[   33.806260] ipu3-cio2 0000:00:14.3: Found supported sensor INT347E:00
[   33.806419] ipu3-cio2 0000:00:14.3: Connected 3 cameras
[   33.809576] ipu3-cio2 0000:00:14.3: enabling device (0000 -> 0002)
[   33.810374] ipu3-cio2 0000:00:14.3: device 0x9d32 (rev: 0x1)
[   33.857395] ipu3-imgu 0000:00:05.0: loaded firmware version irci_irci_ecr-master_20161208_0213_20170112_1500, 17 binaries, 1212984 bytes
[   33.863201] ipu3-imgu 0000:00:05.0: failed initialize subdev media entity (-22)
[   33.863253] ipu3-imgu 0000:00:05.0: failed to register subdev0 ret (-22)
[   33.863276] ipu3-imgu 0000:00:05.0: failed to register pipes (-22)
[   33.863298] ipu3-imgu 0000:00:05.0: failed to create V4L2 devices (-22)
[   33.873064] ov7251 i2c-INT347E:00: supply vdddo not found, using dummy regulator
[   33.873124] ov7251 i2c-INT347E:00: supply vddd not found, using dummy regulator
[   33.873135] ov7251 i2c-INT347E:00: supply vdda not found, using dummy regulator
[   33.879702] ov7251 i2c-INT347E:00: OV7251 revision 7 (1F) detected at address 0x60
[   33.889157] ov8865 i2c-INT347A:00: supply dvdd not found, using dummy regulator
[   33.889199] ov8865 i2c-INT347A:00: supply dovdd not found, using dummy regulator
[   33.889210] ov8865 i2c-INT347A:00: supply avdd not found, using dummy regulator
[   33.890032] ov5693 i2c-INT33BE:00: supply avdd not found, using dummy regulator
[   33.890069] ov5693 i2c-INT33BE:00: supply dovdd not found, using dummy regulator
[   33.890078] ov5693 i2c-INT33BE:00: supply dvdd not found, using dummy regulator
[   33.971431] ov8865 i2c-INT347A:00: Instantiated dw9719 VCM
[   34.011686] ipu3-imgu 0000:00:05.0: wait css idle timeout
[   34.011693] ipu3-imgu: probe of 0000:00:05.0 failed with error -22
[   34.242673] dw9719 i2c-INT347A:00-VCM: supply vdd not found, using dummy regulator

```

**Comment by xorpix** [comment] 2024-02-08 11:41
Same here. Command "cam --list" shows the next:
```
[0:03:04.950699777] [5292] ERROR IPAModule ipa_module.cpp:172 Symbol ipaModuleInfo not found
[0:03:04.950732528] [5292] ERROR IPAModule ipa_module.cpp:292 v4l2-compat.so: IPA module has no valid info
[0:03:04.950784822] [5292]  INFO Camera camera_manager.cpp:284 libcamera v0.2.0
Available cameras:
```

**Comment by LaraWoe** [comment] 2024-02-11 21:00
I think a similar issue here:

Hardware model: Surface Pro 4
Kernel Version: 6.7.2-surface-1
Distribution: Ubuntu 22.04 with libcamera compiled to instructions provided [here](https://github.com/linux-surface/linux-surface/wiki/Camera-Support#build-libcamera-from-the-latest-git-source), I tried the latest version of libcamera as well as version 0.0.4 (based on [this comment](https://github.com/linux-surface/linux-surface/issues/1094#issuecomment-1471894049)) 
Secure Boot disabled

`cam --list` yields no errors, but also does not list available cameras.
```
0:04:49.543116748] [3746]  INFO Camera camera_manager.cpp:284 libcamera v0.2.0+30-38d28cc5
Available cameras:
```
`dmesg | grep ipu3` yields the following (it fails in doing some things, error -22)

```
[   31.510917] ipu3_imgu: module is from the staging directory, the quality is unknown, you have been warned.
[   31.515740] ipu3-imgu 0000:00:05.0: enabling device (0000 -> 0002)
[   31.515957] ipu3-imgu 0000:00:05.0: device 0x1919 (rev: 0x1)
[   31.515979] ipu3-imgu 0000:00:05.0: physical base address 0x00000000a1000000, 4194304 bytes
[   31.582082] ipu3-cio2 0000:00:14.3: Found supported sensor INT33BE:00
[   31.582357] ipu3-cio2 0000:00:14.3: Found supported sensor INT347A:00
[   31.602463] ipu3-cio2 0000:00:14.3: Found supported sensor INT347E:00
[   31.602664] ipu3-cio2 0000:00:14.3: Connected 3 cameras
[   31.603174] ipu3-cio2 0000:00:14.3: enabling device (0000 -> 0002)
[   31.603361] ipu3-cio2 0000:00:14.3: device 0x9d32 (rev: 0x1)
[   31.611259] ipu3-imgu 0000:00:05.0: loaded firmware version irci_irci_ecr-master_20161208_0213_20170112_1500, 17 binaries, 1212984 bytes
[   31.612758] ipu3-imgu 0000:00:05.0: failed initialize subdev media entity (-22)
[   31.612764] ipu3-imgu 0000:00:05.0: failed to register subdev0 ret (-22)
[   31.612767] ipu3-imgu 0000:00:05.0: failed to register pipes (-22)
[   31.612770] ipu3-imgu 0000:00:05.0: failed to create V4L2 devices (-22)
[   31.731091] ipu3-imgu 0000:00:05.0: wait css idle timeout
[   31.731096] ipu3-imgu: probe of 0000:00:05.0 failed with error -22
```

Similar to the cases above, e.g. `dmesg | grep ov5693` yields this
```
[   31.598188] ov5693 i2c-INT33BE:00: supply avdd not found, using dummy regulator
[   31.598233] ov5693 i2c-INT33BE:00: supply dovdd not found, using dummy regulator
[   31.598245] ov5693 i2c-INT33BE:00: supply dvdd not found, using dummy regulator
```

**Comment by absorb-it** [comment] 2024-02-29 09:46
Hi,

the issue was caused by introducing [a pad flag check](https://github.com/torvalds/linux/commit/deb866f9e3a45ae058b21765feeffae6aea6a193) into the linux kernel starting from [v6.7-rc1](https://github.com/torvalds/linux/releases/tag/v6.7-rc1). Some fix is also available at the [kernel mailing list](https://lkml.org/lkml/2023/12/28/189), I have no idea why it was not implemented into the kernel and how to trigger some progress there. Any idea?

Downgraded to linux-image-6.6.11-surface-1 and camera is working again.

Best regards, Rene

**Comment by tormodvolden** [comment] 2024-03-02 13:05
See also https://github.com/linux-surface/linux-surface/issues/1359#issuecomment-1974789494 for a workaround.

**Comment by qzed** [comment] 2024-03-16 20:30
Since the patch linked above has been included in the lastest releases, could anyone confirm that the cameras do indeed work and that we can close this issue?

**Comment by tkaefer** [comment] 2024-03-16 20:35
On my SP 6 with Ubuntu 23.10 and the 6.7.9 kernel the Cameras work - somewhat the back camera is just turned upside down (tested with qcam and cheese).

**Comment by qzed** [comment] 2024-03-16 20:46
@tkaefer Thanks! I'll close this then.

**Closed by qzed** 2024-03-16 20:46 UTC
