### ISSUE TITLE
SP7 Pen Connected but not detected/kernel module install failed (key rejected)

### ISSUE THREAD

**Issue by jtrenaud1s** [linux-surface/linux-surface#914] opened 2022-08-27 04:33 UTC
My pen currently is not working.

### Environment

- Hardware model: Surface Pro 7
- Kernel version: 5.19
- Distribution: Ubuntu 22.04
- Secure Boot: Enabled

<details><summary>

Not using any dkms

I've built the latest iptsd from the upstream repo, it works fine:
```
iptsd.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/lib/systemd/system/iptsd.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-08-26 22:14:28 CDT; 1h 1min ago
       Docs: https://github.com/linux-surface/iptsd
   Main PID: 4917 (iptsd)
      Tasks: 1 (limit: 8981)
     Memory: 372.0K
        CPU: 12.815s
     CGroup: /system.slice/iptsd.service
             └─4917 /usr/bin/iptsd

Aug 26 22:14:28 subspace systemd[1]: Started Intel Precise Touch & Stylus Daemon.
```
and
```
$ sudo dmesg | grep 'ipts\|IPTS'
[    3.550794] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Starting IPTS
[    3.553950] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Device 045E:099F ready
[   92.962664] input: IPTS Touch as /devices/virtual/input/input40
[   92.963028] input: IPTS Stylus as /devices/virtual/input/input41
```
I can't build ithc or the newer version of ipts because my signing key keeps getting rejected.
```
ithc/ $ make && sudo make install ---- fails to sign
```
as a result, I generated and enrolled my own MOK, signed the already built and unsigned ithc.ko, and this is the result:

```
$ sudo modprobe ithc
modprobe: ERROR: could not insert 'ithc': Key was rejected by service
```
Can verify the module is signed:
```
$ modinfo ithc.ko
filename:       /lib/modules/5.19.2-surface/extra/ithc.ko
license:        Dual BSD/GPL
description:    Intel Touch Host Controller driver
srcversion:     7B41C624B6A896626A8D553
alias:          pci:v00008086d000043D1sv*sd*bc*sc*i*
alias:          pci:v00008086d000043D0sv*sd*bc*sc*i*
alias:          pci:v00008086d0000A0D1sv*sd*bc*sc*i*
alias:          pci:v00008086d0000A0D0sv*sd*bc*sc*i*
alias:          pci:v00008086d000098D1sv*sd*bc*sc*i*
alias:          pci:v00008086d000098D0sv*sd*bc*sc*i*
depends:        hid
retpoline:      Y
name:           ithc
vermagic:       5.19.2-surface SMP preempt mod_unload modversions 
sig_id:         PKCS#7
signer:         Secure Boot Signing
sig_key:        70:A0:A5:E5:80:69:90:01:36:42:F0:C2:52:36:5C:E7:8E:7E:0A:46
sig_hashalgo:   sha256
signature:      29:15:78:07:AC:29:7F:D8:5C:7A:FF:A4:47:42:AB:6D:03:EA:4B:98:
		C3:BE:8A:73:63:E2:99:BC:4C:1D:D9:AA:EB:58:AC:B8:82:9D:AD:00:
		DD:53:05:CD:FE:74:7B:BE:A0:5E:53:AA:C0:FA:CC:D8:55:F1:1A:C3:
		8C:DF:9A:B4:75:70:69:1B:D6:74:C3:40:9C:78:42:29:DF:44:90:BC:
		68:4A:4A:FD:2A:89:77:81:4B:DC:69:0F:84:4D:79:12:06:C6:72:99:
		A3:6D:E1:F9:2E:0A:5E:70:39:F6:61:97:F2:DD:F5:3D:66:A0:5D:93:
		38:A8:3E:5F:07:14:8C:92:A7:EC:66:3A:B2:2F:20:02:59:D0:75:91:
		D7:40:3C:D0:2D:5E:B9:2A:67:C4:42:29:D0:B3:BE:A5:B4:62:54:9B:
		2E:E9:A0:68:BF:25:20:C1:59:E3:DF:7E:68:A9:2D:1F:0E:90:B1:1E:
		2B:59:AE:54:FD:5D:7D:03:B2:57:3D:94:D5:D7:2B:D8:54:D3:B6:DF:
		0F:40:DA:BB:1E:E1:85:95:75:C0:15:72:53:7B:BD:C7:74:6D:C1:A0:
		7E:ED:93:A1:16:D0:D5:8D:EC:62:E7:03:4B:72:A2:FF:48:DC:7A:B5:
		77:88:F9:2F:B3:C4:74:48:4A:07:42:53:50:5C:01:38
parm:           poll:Use polling instead of interrupts (bool)
parm:           hid:Operate as an HID transport driver instead of an input driver (bool)
parm:           rx0:Use DMA RX channel 0 (bool)
parm:           rx1:Use DMA RX channel 1 (bool)
parm:           logregs:Log changes in register values (for debugging) (bool)

```
can verify I have all dependencies built

intel-precise-touch: same problem as ithc

From other issues, I understand I may not need ithc and just ipts, but it's having the same issue, having the key it was signed with rejected, so it can't be installed.

My assumption is that the pen isn't working because I don't have linux-surface/intel-precise-touch built and installed.

Touch is fine (single finger), can scroll with it and draw on openBoard with one finger.</summary>

The pen is recognized when connected on bluetooth, it just doesn't draw.
```
[  760.910015] Loading of module with unavailable key is rejected
[  826.575907] Loading of module with unavailable key is rejected
[  867.165367] Loading of module with unavailable key is rejected
[ 1031.905953] Loading of module with unavailable key is rejected
[ 1143.267670] Loading of module with unavailable key is rejected
[ 1719.999498] Loading of module with unavailable key is rejected

[ 2911.708214] input: Surface Pen Keyboard as /devices/virtual/misc/uhid/0005:045E:0921.0003/input/input42
[ 2911.708341] input: Surface Pen as /devices/virtual/misc/uhid/0005:045E:0921.0003/input/input43
[ 2911.708465] hid-generic 0005:045E:0921.0003: input,hidraw1: BLUETOOTH HID v0.30 Keyboard [Surface Pen] on 3c:9c:0f:f2:4f:0d
[ 3860.200834] input: Surface Pen Keyboard as /devices/virtual/misc/uhid/0005:045E:0921.0004/input/input45
[ 3860.201072] input: Surface Pen as /devices/virtual/misc/uhid/0005:045E:0921.0004/input/input46
[ 3860.201280] hid-generic 0005:045E:0921.0004: input,hidraw1: BLUETOOTH HID v0.30 Keyboard [Surface Pen] on 3c:9c:0f:f2:4f:0d
[ 4221.825942] input: Surface Pen Keyboard as /devices/virtual/misc/uhid/0005:045E:0921.0005/input/input48
[ 4221.826211] input: Surface Pen as /devices/virtual/misc/uhid/0005:045E:0921.0005/input/input49
[ 4221.826535] hid-generic 0005:045E:0921.0005: input,hidraw1: BLUETOOTH HID v0.30 Keyboard [Surface Pen] on 3c:9c:0f:f2:4f:0d
```

</details>

I feel like if I can get the kernel to accept the key I signed the ithc and ipts modules with, it would probably start working.

Also off-topic but maybe related, I noticed with bluetooth, my mouse and pen disconnect after a minute or so of inactivity. Not sure if that's intended, I've tried a bluetooth fix for ubuntu in general but it didn't solve the problem

**Comment by StollD** [comment] 2022-08-27 07:34
Duplicate of #906, 5.19.4 should fix this.

Also, you only need one of ipts or ithc. Surface Pro 7 needs ipts, while everything after Surface Pro 7+ needs ithc.

**Closed by StollD** 2022-08-27 07:34 UTC
