### ISSUE TITLE
liblpf: failed to find valid kernel BTF

### ISSUE THREAD

**Issue by 1900011604** [linux-surface/linux-surface#382] opened 2021-01-14 13:03 UTC
**OS: Manjaro 21.0pre-1**
**Kernel: Linux-Arch-5.10.6-surface**

Problem:
When I open my desktop it says:
```
liblpf: failed to find valid kernel BTF
liblpf: Error loading vmlinux BTF -3
liblpf: failed to load object 'iterators_bpf': -3
Failed load could be due to wrong endianess
```

**Comment by qzed** [comment] 2021-01-14 15:10
Closing as duplicate of #375, please refer to that.

**Closed by qzed** 2021-01-14 15:10 UTC
