### ISSUE TITLE
SB2: 5GHz Wifi connection not working

### ISSUE THREAD

**Issue by eggplanting** [linux-surface/linux-surface#137] opened 2020-03-28 16:33 UTC
Hi together,

with the latest Linux-Surface kernel, my SB2 is not able to connect to a 5 GHz SSID. I tried to connect to multiple 5GHz Channels (changed my wifi config multiple times), ranging from 36 to 140. I'm able to see each 5GHZ SSID, but not able to connect. After connecting to the SSID, the network manager tells me that my WPA2 PSK is wrong (which isn't). Connecting to 2.4 GHz SSIDs with the same passphrase works instantly.

In 2019, Microsoft released a wifi driver which brought this issue. I had exactly the same issue with Windows for several months: https://answers.microsoft.com/en-us/surface/forum/surfbook-surfnetwork/marvell-semiconductor-inc-net-156817013110-wifi/033b3613-135e-430a-952f-46440c764f58

It was fixed on Windows with the latest Marvell driver. My guess is, that the used Marvell driver with this kernel is based on an older version including this bug.

- Hardware model: Surface Book 2
- Kernel version: 5.5.13-arch1-1-surface #1 SMP PREEMPT Fri, 27 Mar 2020 10:27:33 +0000 x86_64 GNU/Linu
- Distribution: Arch Linux
- Used Access Points: Ubiquiti Unifi AP HD

**Comment by qzed** [comment] 2020-03-29 00:32
Linux doesn't really have a concept of different driver versions. The latest version considered stable is always the one in the latest kernel release, which at the moment 5.5. There are in general a lot of problems with this driver (see #70) and unless Marvell sends some changes to the kernel we're probably stuck with that, as no one of us has much experience with that driver and we further suspect that most of these issues might also be a firmware problem (which, even if we had time to learn about the in-kernel driver, we couldn't do much about because it's a closed-source blob).

Let's keep this issue open as it seems substantially different from the usual power-save/suspend issues in #70.

**Comment by eggplanting** [comment] 2020-03-29 17:47
Thanks for your response.

For Windows, the issue was fixed with following driver versions:
15.68.17017.115
15.68.17017.112

Source: http://www.catalog.update.microsoft.com/Search.aspx?q=marvell+avastar

**Comment by jonas2515** [comment] 2021-04-03 08:46
Reading through the Windows issue reports, this appears to be an issue with 802.11r protocol support in the firmware, so this is a duplicate of https://github.com/linux-surface/linux-surface/issues/386.

**Comment by jonas2515** [comment] 2021-04-04 08:50
Closing this one in favour of https://github.com/linux-surface/linux-surface/issues/386, it would be great if you could share the output of `iw dev wlp1s0 scan` for the network the surface doesn't connect to on that issue.

**Closed by jonas2515** 2021-04-04 08:50 UTC
Labels: A: mwifiex, D: Surface Book 2
