### ISSUE TITLE
SP7 touchscreen unresponsive after waking from suspend (5.8.5)

### ISSUE THREAD

**Issue by danieldeng2** [linux-surface/linux-surface#274] opened 2020-08-30 16:17 UTC
The solution mentioned in #89 no longer seems to be working for 5.8+
Manually typing `rmmod ipts `and `modprobe ipts` isn't working either with the new drivers

```
[daniel@surface-pro-7 ~]$ sudo systemctl status iptsd.service
● iptsd.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/usr/lib/systemd/system/iptsd.service; enabled; vendor pre>
     Active: inactive (dead) since Sun 2020-08-30 16:48:45 BST; 2s ago
       Docs: https://github.com/linux-surface/iptsd
    Process: 4149 ExecStart=/usr/bin/iptsd (code=exited, status=0/SUCCESS)
   Main PID: 4149 (code=exited, status=0/SUCCESS)

Aug 30 16:48:45 surface-pro-7 iptsd[4149]: open /dev/ipts: no such device
Aug 30 16:48:45 surface-pro-7 iptsd[4149]: main.(*IptsControl).Start
Aug 30 16:48:45 surface-pro-7 iptsd[4149]:         /__w/iptsd/iptsd/pkg/fedora/>
Aug 30 16:48:45 surface-pro-7 iptsd[4149]: main.main
Aug 30 16:48:45 surface-pro-7 iptsd[4149]:         /__w/iptsd/iptsd/pkg/fedora/>
Aug 30 16:48:45 surface-pro-7 iptsd[4149]: runtime.main
Aug 30 16:48:45 surface-pro-7 iptsd[4149]:         /usr/lib/golang/src/runtime/>
Aug 30 16:48:45 surface-pro-7 iptsd[4149]: runtime.goexit
Aug 30 16:48:45 surface-pro-7 iptsd[4149]:         /usr/lib/golang/src/runtime/>
Aug 30 16:48:45 surface-pro-7 systemd[1]: iptsd.service: Succeeded.
```

log from fedora 32 running 5.8.5-1.surface.fc32.x86_64 #1 SMP Fri Aug 28 16:40:57 UTC.

**Comment by danieldeng2** [comment] 2020-08-30 16:41
downgrading back to 5.7.17 until someone writes a new script for 5.8+

**Comment by StollD** [comment] 2020-08-31 13:36
Spamming the same report under 4 different issues (one of them being a new one) doesn't help, it only confuses and annoys everybody involved (users + maintainers).

I posted and updated script in the original thread for this issue. Closing this as a duplicate of #89

**Closed by StollD** 2020-08-31 13:36 UTC
