### ISSUE TITLE
Signature from "linux-surface" is invalid

### ISSUE THREAD

**Issue by 1900011604** [linux-surface/linux-surface#349] opened 2020-12-04 00:16 UTC
```
error: linux-surface: signature from "linux-surface" is invalid
:: File /var/cache/pacman/pkg/linux-surface-5.9.11.arch2-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.
```

**Comment by 1900011604** [comment] 2020-12-04 00:21
I have operated these commands:

    wget -qO - https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc \
    | sudo pacman-key --add -
    sudo pacman-key --finger 56C464BAAC421453
    sudo pacman-key --lsign-key 56C464BAAC421453

**Comment by 1900011604** [comment] 2020-12-04 04:58
But when I download them from github and run:
```
sudo cp ~/linux-surface-5.9.11.arch2-1-x86_64.pkg.tar.zst /var/cache/pacman/pkg/
sudo cp ~/linux-surface-5.9.11.arch2-1-x86_64.pkg.tar.zst linux-surface-headers-5.9.11.arch2-1-x86_64.pkg.tar.zst /var/cache/pacman/pkg/ 
LANG=C sudo pacman -Syyu
```
It succeeded.

**Comment by qzed** [comment] 2020-12-05 02:48
I can't reproduce this on a new Arch container. Are you sure all `pacman-key` commands were executed successfully? Any error messages? I assume you also ran `pacman -Syu` after adding the repo?

**Comment by 1900011604** [comment] 2020-12-05 03:08
No error messages, but I did not ran `pacman -Syu`, maybe it is it's fault.

**Comment by qzed** [comment] 2020-12-05 03:47
Does reinstalling `linux-surface` via `pacman -S linux-surface` work now?

**Comment by Bodhi-Teraguchi** [comment] 2021-02-11 03:12
hey I am having this same problem on fedora workstation 33 on Surface Pro 4.

**Comment by StollD** [comment] 2021-02-11 06:00
What error message do you get?

 DNF on fedora should ask you to import missing keys automatically. If not you can try this command.
```bash
sudo rpm --import https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc
```

**Comment by Bodhi-Teraguchi** [comment] 2021-02-11 17:48
Thanks for the reply!  I tried 
``sudo rpm --import https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc``  With no improvement.  

This is the full message I get when I try to boot with secure boot enabled:
``error: ../../grub-core/loader/i386/efi/linux.c:316: (hd0,gp2) /vmlinuz-5.10.13-1.surface.fc33.x86-64 has invalid signature.
error: ../../grub-core/loader/i386/efi/linux.c:208: you need to load the kernel first.
Press any key to continue...``

I wasn't sure if i should have made a new issue since it is slightly different.

**Comment by StollD** [comment] 2021-02-13 08:09
Thats a secureboot error, not a package signing error. Did you install `surface-secureboot` and follow the instructions it prints to the terminal?

**Comment by Bodhi-Teraguchi** [comment] 2021-02-13 18:02
You mean it prints from DNF? I did see any instructions print out, is their another place to look?

**Comment by StollD** [comment] 2021-02-14 09:59
Yes, DNF should print the instructions. Basically, installing the package will enroll our secureboot certificate. On the next reboot you should see a blue interface that asks you to confirm enrolling the  key. When it asks you for a password, you need to enter `surface`.

**Comment by Bodhi-Teraguchi** [comment] 2021-02-14 15:16
OK! No instructions printed but I did what you said and it works now!

**Comment by StollD** [comment] 2021-02-19 10:51
Since this issue has been solved (twice), I'm going to close this.

**Closed by StollD** 2021-02-19 10:51 UTC
