### ISSUE TITLE
surface3-spi (touchscreen driver): not usable with DMA

### ISSUE THREAD

**Issue by kitakar5525** [linux-surface/linux-surface#76] opened 2020-02-08 22:41 UTC
[Description of the bug or feature]
I inform here that I filed a bug to Bugzilla regarding Surface 3 touch input crashing after making touch input two times:
https://bugzilla.kernel.org/show_bug.cgi?id=206403

The workaround is already available on this repo as patch [surface3-spi.patch](https://github.com/linux-surface/linux-surface/blob/2fb7e9ae91350098db9a280277f424272816a9ab/patches/5.5/0002-surface3-spi.patch).

If you use with mainline kernel, the following workaround is available:
```bash
# run the following commands *after* touch input crashed
sudo modprobe -r spi_pxa2xx_platform
sudo modprobe spi_pxa2xx_platform
```

### Environment

- Hardware model: Surface 3
- Kernel version: At least on 4.19 or later
- Distribution: At least Ubuntu / Arch Linux / Fedora with their kernels

For details, visit the buglink.

**Comment by jack999123** [comment] 2020-05-20 13:37
wanna know if  “the touch input" supports the version deepin v20 .thanks so much

**Comment by kitakar5525** [comment] 2020-05-21 09:41
Deepin is a Debian-based distro. So, as long as you use linux-surface kernel for debian, there should be no problems regarding touch input.

**Comment by kitakar5525** [comment] 2020-07-11 10:22
Informing that upstream fix for DMA is available here: https://git.kernel.org/pub/scm/linux/kernel/git/vkoul/dmaengine.git/commit/?id=99ba8b9b0d9780e9937eb1d488d120e9e5c2533d

I'll drop the surface3-spi.patch once the upstream fix is available for v5.7, v5.4 and v4.19.

**Comment by kitakar5525** [comment] 2020-07-24 13:24
The fix is now in mainline (v5.8-rc6): https://github.com/torvalds/linux/commit/99ba8b9b0d9780e9937eb1d488d120e9e5c2533d

and got backported to
- v5.7.10 (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.7.y&id=838f21b2e14d6d555aade5f2ece41be09750f0b3)
- v5.4.53 (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.4.y&id=e6b46f01d9951bce04ec87b8df92ee8bb48802cb)

Now that the `surface3-spi` patch is no longer needed, I dropped it (https://github.com/linux-surface/linux-surface/pull/237)

#### Note: v4.19

The upstream fix isn't backported to v4.19 or below LTS kernels by upstream. So, I backported the commit to v4.19-surface-devel branch (https://github.com/linux-surface/kernel/commit/94678ca738de51ac84cea6c26c6aa6998e37f57e) and generated as `surface3-touchscreen-dma-fix.patch` in this repo.

#### requesting upstream to backport the commit to older LTS kernels?

The best thing is that it will be backported to also v4.19 by upstream at some point. The commit can't be cherry-picked as-is to such older LTS kernels. I guess this is the reason it was skipped.

I want to try to ask if the patch can be backported also to such older LTS kernels. But I'm not familiar with how patches are backported to LTS kernels by upstream. If someone know the upstream backport process, let me know.

I keep this issue open until it's backported to upstream v4.19.

**Comment by atmouse-** [comment] 2020-10-08 06:23
Hey gentlemen, I m still got surface3_spi hung under kernel 5.8.13 w/ [patched](https://github.com/linux-surface/linux-surface/tree/master/patches/5.8)
```
Linux 5.8.13-1-surface3 #71 SMP PREEMPT Sat, 03 Oct 2020 11:56:55 +0000 x86_64 GNU/Linux
```
```
[16361.718394] Surface3-spi spi-MSHW0037:00: SPI transfer timed out
[16361.718600] spi_master spi1: failed to transfer one message from queue
```

**Comment by kitakar5525** [comment] 2020-10-10 11:25
Hmm, I haven't encountered the `SPI transfer timed out` issue after the patch.

But I feel I do have issue when I load atomisp drivers. Weird enough, but when I load atomisp drivers, touchscreen stops working without showing any dmesg log.
I'd like to look into what's happening when I have time...

**Comment by saschanaz** [comment] 2020-10-29 11:51
I too have the SPI transfer timed out errors. Initially the touchscreen works well but it suddenly becomes unresponsive several dozens of minutes later, and then I can see those errors when I type Control+Alt+F3 to open the shell.

**Comment by atmouse-** [comment] 2020-10-29 16:06
> but it suddenly becomes unresponsive several dozens of minutes later

Maybe you need disable power idle policy C1+
add this boot-up parameters to kernel cmdline
```
intel_idle.max_cstate=1 i915.enable_dc=0
```

**Comment by saschanaz** [comment] 2020-10-29 16:54
I don't think it's the power state because it happens when I'm actively using the device. But I'll try.

**Comment by hadess** [comment] 2021-01-09 09:19
The work-around patches mentioned in https://github.com/linux-surface/linux-surface/issues/76#issuecomment-663536664 were added to the surface kernel, and then removed when an upstream fix was committed. See https://github.com/linux-surface/linux-surface/issues/368#issuecomment-751800578

This issue can probably be closed.

> I don't think it's the power state because it happens when (and only when) I'm actively using the device. But I'll try.

I've seen a bunch of hangs with recent surface kernels, one was likely caused by the Marvell Wi-Fi (for a change), but twice the machine froze while I was using it. Forcing it off and rebooting showed the "low battery" icon. It seems that the machine will just stop working when the battery is too low, or something (else) causes the touchscreen driver to crash.

**Comment by qzed** [comment] 2021-01-09 16:56
> The work-around patches mentioned in [#76 (comment)](https://github.com/linux-surface/linux-surface/issues/76#issuecomment-663536664) were added to the surface kernel, and then removed when an upstream fix was committed. See [#368 (comment)](https://github.com/linux-surface/linux-surface/issues/368#issuecomment-751800578)
> 
> This issue can probably be closed.

Right, thanks for the ping.

Feel free to open a new issue for any remaining problems.

**Closed by qzed** 2021-01-09 16:56 UTC
Labels: C: bug (upstream), D: Surface 3

**Comment by PaweX** [comment] 2022-09-07 12:41
I have just installed Arch Linux on my S3 with the newest surface kernel, and have this issue. Touchscreen crashes in a random moment, last time e.g. when I switched off on-screen keyboard. Pressing power button to logout and login again makes the touchscreen working again, but temporary to a next crash. It's very frustrating to use surface in this way, how to fix it in the newest kernel. Does anyone still have this issue?


> I've seen a bunch of hangs with recent surface kernels, one was likely caused by the Marvell Wi-Fi (for a change), but twice the machine froze while I was using it. Forcing it off and rebooting showed the "low battery" icon. It seems that the machine will just stop working when the battery is too low, or something (else) causes the touchscreen driver to crash.

My surface is charged in around 75%. And it looks like the problem is not caused by the battery.

**Comment by NP-chaonay** [comment] 2022-09-17 19:09
> And it looks like the problem is not caused by the battery.

so even battery is not low, it show low battery?

**Comment by Vaasis** [comment] 2022-10-13 17:35
> I have just installed Arch Linux on my S3 with the newest surface kernel (5.19.6), and have this issue. Touchscreen crashes in random moments, last time e.g. when I switched off on-screen keyboard. Pressing power button to put the tablet to sleep mode, then waking it up makes the touchscreen working again, but temporary to a next crash. It's very frustrating to use surface in this way, how to fix it in the newest kernel? Does anyone still have this issue? Also after typing `libwacom-list-local-devices` I have such output: `/dev/input/event11 is a tablet but not supported by libwacom`. I've installed libwacom-surface from AUR.
> 
> > I've seen a bunch of hangs with recent surface kernels, one was likely caused by the Marvell Wi-Fi (for a change), but twice the machine froze while I was using it. Forcing it off and rebooting showed the "low battery" icon. It seems that the machine will just stop working when the battery is too low, or something (else) causes the touchscreen driver to crash.
> 
> My surface is charged in around 75%, and I also tested it when it was 100%. And it looks like the problem is not caused by the battery.

Pasting here the same comment that originally posted in https://github.com/jakeday/linux-surface/issues/596 (did not know that wasn't maintained anymore):


I'm having the same issue running Fedora 36. Is there a way to apply the surface3-spi patch in the current kernel version, or perhaps an alternate method to switch between DMA/PIO for the touchscreen driver?

Not sure what causes the issue in the first place, but considering im in the lowest specced S3 (64GB eMMC and 2GB RAM) maybe the swap needs to be bigger, or GNOME with Wayland might be using too much resources?

Having tried ChromeOS Flex, it didn't present any touchscreen issues, though it did have other problems such as being stuck in 100% brightness; no auto-rotation and so on.

**Comment by NP-chaonay** [comment] 2022-10-14 01:57
> Not sure what causes the issue in the first place, but considering im in the lowest specced S3 (64GB eMMC and 2GB RAM) maybe the swap needs to be bigger, or GNOME with Wayland might be using too much resources?

Maybe If i not wrong , the actual root cause is your memory is too low

Despite of chaning ram amount, you could just add swap I recommended not to exceed than 2-4 GB to prevent to high I/O load

Q: But  why it good work on Win8 ?
A: Windows 8 and prior dont have much access of SSD so it gain speed, but for Win10 and up, when it does and when ram is not enough, disk will be using aggreaggressive too, so I/O load slow >>> paging slow >> system slow



> GNOME with Wayland might be using too much resources?

if it use too much ram then you required to using xfce/lxde
You have to cut out everything that eat ram

TBH since thw computer is not old to 10 year, I very recommended to upgrade ram,
If you consider that the spec is too low, then using higher spec
nowday average usage is 8gb on core i3/r3

**Comment by Vaasis** [comment] 2022-10-14 02:14
> > Not sure what causes the issue in the first place, but considering im in the lowest specced S3 (64GB eMMC and 2GB RAM) maybe the swap needs to be bigger, or GNOME with Wayland might be using too much resources?
> 
> Maybe If i not wrong , the actual root cause is your memory is too low
> 
> Despite of chaning ram amount, you could just add swap I recommended not to exceed than 2-4 GB to prevent to high I/O load
> 
> Q: But why it good work on Win8 ? A: Windows 8 and prior dont have much access of SSD so it gain speed, but for Win10 and up, when it does and when ram is not enough, disk will be using aggreaggressive too, so I/O load slow >>> paging slow >> system slow
> 
> > GNOME with Wayland might be using too much resources?
> 
> if it use too much ram then you required to using xfce/lxde You have to cut out everything that eat ram
> 
> TBH since thw computer is not old to 10 year, I very recommended to upgrade ram, If you consider that the spec is too low, then using higher spec nowday average usage is 8gb on core i3/r3

I'd love to add more RAM (4GB would probably be fine for my use case) but it's all a SoC, so soldered ram straight to the motherboard (i'd like to upgrade the internal storage to 128GB SSD too but same problem)

I'll try to increase the swap file and report back asap.
