### ISSUE TITLE
Update  creates boot issue 'decompression failed with status 6'

### ISSUE THREAD

**Issue by bbelmar** [linux-surface/linux-surface#1270] opened 2023-10-15 07:36 UTC
on Surfacebook 2 on ubuntu 23.10

I found this kernel on October 12 and installed, It worked great. Until today at startup I got a notification from the update manager offering new linux surface kernel updates. (6.5.6 i believe). I updated and then it asked to reboot. On reboot I got the failure message " decompression failed with status 6" and boot up would stop there, so i cant log in. 

I booted with ubunut's kernel 6.5 and re installed the linux surface drivers from that ubuntu kernel, but it created the same issue again. 
I reverted to a TIMESHIFT image I had created after the first Linux Surface kernel install where all was working and thats what im running now. 

![image](https://github.com/linux-surface/linux-surface/assets/29048524/0f1de5c7-55f3-4014-95c6-72c6f6c032f7)

I keep getting bugged by the updater to update but i know it will break the bootup. 
If I do a sudo apt update... will it take this kernel update too?

thanks

**Comment by qzed** [comment] 2023-10-15 08:15
Do you happen to know which specific version caused the problem?
6.5.6-surface-1 or 6.5.6-surface-2? Upstream sources seem to have changed
the module compression to zstd in 6.5.6, which wasn't supported by older
distros. We changed it to xz in 6.5.6-surface-2 in hope that this would be
supported across the board. So we would need to know whether xz fixes this
or whether it can't be used either. A last alternative would be gzip before
we go with uncompressed modules.

FYI, you should be able to install/downgrade to older kernel versions by
installing the specific versioned package.

**Comment by bbelmar** [comment] 2023-10-15 08:37
Hey thanks for being so quick to reply
Im running 6.5.6.1 on ubuntu 23.10 now and it works great, although surface control application doesnt do make any changes with the set commands. I can only get info. I installed this a few days ago.
I believe I remember seeing the new update was 6.5.6.2 (almost sure)

**Comment by Zather1995** [comment] 2023-10-15 16:27
I had the same issue on my Surface Pro 6 and in 6.5.6-surface-2 and it now works with 6.5.6-surface-1 so i can confirm the issue was created for me in the latest version.

**Comment by qzed** [comment] 2023-10-15 18:42
Alright, I've changed the config to disable module compression. New packages are building.

**Comment by nobu1308** [comment] 2023-10-16 06:48
I got the same error yesterday with Surface Pro 8 + Ubuntu 23.10. Just rebooted with the generic kernel, upgraded to the latest version by Software Updater and the problem is gone. Thanks!

**Comment by qzed** [comment] 2023-10-16 08:37
Closing this as solved then. Let me know if thia issue pops up again.

**Closed by qzed** 2023-10-16 08:37 UTC
