### ISSUE TITLE
No Desktop on Ubuntu 22.04 for SP8

### ISSUE THREAD

**Issue by therealdandecker** [linux-surface/linux-surface#786] opened 2022-04-04 00:58 UTC
Naturally inclined to experiment I installed Ubuntu 22.04 beta on my Surface Pro 8. All good after installation (very snappy, kudos to the Canonical team.)

Did a minimal install. Added surface repo and packages, and secure boot key. 

After enrolling MOK key and rebooting the entire GUI environment was blown away and I was left with a command line. 

This is their public beta of Ubuntu 22.04 Jammy Jellyfish. 

Running Surface Pro 8 11th gen i5. Will include dmsg tomorrow but opened this more as a heads up for anyone experimenting and may be isolated to something silly done along the way.

**Comment by nishant85** [comment] 2022-04-16 11:30
I am also facing the same issue on my Surface Go.

**Comment by raikesy** [comment] 2022-04-21 19:25
Same issue with the 22.04 release version. Reinstalling libwacom-surface didn't seem to do anything for me.

**Comment by biigii** [comment] 2022-04-23 05:43
same issue here, thanks to @raikesy removing libwacom-surface and reinstalling ubuntu-desktop solved the problem

**Comment by RichardODonoghue** [comment] 2022-04-26 08:52
I had the same issue but in my case removing libwacom-surface and reinstalling ubuntu desktop left me with more issues than i had previously. For some reason I lost full keyboard and mouse support too on my SL4.

**Comment by qzed** [comment] 2022-04-27 15:17
Closing as duplicate of #783.

**Closed by qzed** 2022-04-27 15:17 UTC
