### ISSUE TITLE
No Automatic Screen Rotation on SP8

### ISSUE THREAD

**Issue by k4ever** [linux-surface/linux-surface#864] opened 2022-06-24 19:27 UTC
Device: Surface Pro 8 Core i5
Distribution: EndeavourOS (Arch Linux)
Surface Kernel Version: 5.18.5-arch1-1-surface
Desktop: KDE Plasma 5.25.1(Wayland), GNOME 42 (Wayland)

I recently installed the Arch version of SurfaceLinux kernel on my SP8. I'm running EndeavourOS with the KDE Plasma 5.25.1 and GNOME 42 desktops installed. Screen autorotation is not working. 

I have iio-sensor-proxy version 3.3-1 installed. When I start the service with systemctl start iio-sensor-proxy, I get no output. When I run sudo /usr/lib/iio-sensor-proxy -r -v, I get the following output:

** (iio-sensor-proxy:4000): DEBUG: 15:23:02.508: No sensors or missing kernel drivers for the sensors

When I run lsmod | grep iio, I also get no output. What am I missing? Has anyone gotten screen autorotation to work on the SP8?

**Comment by qzed** [comment] 2022-06-25 15:47
Seems like a duplicate of #861.

**Comment by qzed** [comment] 2022-06-25 18:28
Auto-rotation should work with iio-sensor-proxy and the patch resulting from #861. So I'm closing this as duplicate.

**Closed by qzed** 2022-06-25 18:28 UTC

**Comment by k4ever** [comment] 2022-06-25 19:24
Thanks! Understood. I apologize for not closing it once the OP from #861 verified that the lack of sensors also affected the screen rotation.  Thanks for your work!

**Comment by qzed** [comment] 2022-06-25 19:25
No worries.
