### ISSUE TITLE
[Surface Pro 9] Kernel 6.10.5 causes system to panic

### ISSUE THREAD

**Issue by wtfcxt** [linux-surface/linux-surface#1537] opened 2024-08-17 21:51 UTC
[Description of the bug or feature]
I just updated to kernel version 6.10.5 and now my Surface gets stuck at `Listening on systemd-rfkill.socket - Load/Save RF Kill Switch Statusu /dev/rfkill Watch.` when looking at verbose boot. The entire system just halts, I now downgraded to 6.9.3-surface-2 and my system is bootable again.

### Environment

- Hardware model: Surface Pro 9 (i7-1255U, 16GB RAM)
- Kernel version: 6.10.5-surface-1
- Distribution: Ubuntu

<details><summary>`dmesg` output</summary>

`Dmesg output is too long for pasting it into an issue`
https://pastebin.ubuntu.com/p/7qJJPm96FJ/

</details>

**Comment by wtfcxt** [comment] 2024-08-17 22:08
Will need to check but looks like this might be related to #1533

**Comment by wtfcxt** [comment] 2024-08-17 22:33
![IMG_20240818_003216191.jpg](https://github.com/user-attachments/assets/c25e96f7-d1e3-479a-bd38-89f1322777bc)

Looks like the system is panicing. It doesn't always print the panic, that's why I only found out now.

**Comment by wtfcxt** [comment] 2024-08-17 22:42
![IMG_20240818_004134769.jpg](https://github.com/user-attachments/assets/4dab3ef5-e613-4e8c-aa49-126092f929fd)

Blacklisting `iwlwifi` also causes the system to panic, I am running out of ideas. But this also happens when using the mainline Kernel.

**Comment by qzed** [comment] 2024-08-17 23:05
Based on the logs, this looks like #1516. Can you try the workaround [here](https://github.com/linux-surface/linux-surface/issues/1516#issuecomment-2269662870)?

For now, I'll close this as duplicate of #1516, but please let me know if the workaround does not work. Then we can re-open this again.

**Closed by qzed** 2024-08-17 23:05 UTC

**Comment by wtfcxt** [comment] 2024-08-17 23:16
> Based on the logs, this looks like #1516. Can you try the workaround [here](https://github.com/linux-surface/linux-surface/issues/1516#issuecomment-2269662870)?
> 
> For now, I'll close this as duplicate of #1516, but please let me know if the workaround does not work. Then we can re-open this again.

This doesn't work. I have blacklisted both of them and the system still panics. Doesn't matter if I'm using linux-surface or the mainline kernel.

Mainline:
![IMG_20240818_011409608.jpg](https://github.com/user-attachments/assets/0c85cd0d-cd43-43b1-8583-95f67a3c98c0)

Linux-Surface:
![IMG_20240818_011627059.jpg](https://github.com/user-attachments/assets/c0806ba3-26a6-45e6-aaad-512cce3e0fe4)

**Comment by wtfcxt** [comment] 2024-08-17 23:20
I'm actually a little bit confused since it's still saying something about ipu6. But I tried adding it to the kernel command line and I also tried blacklisting it at /etc/modprobe.d/blacklist.conf

![IMG_20240818_012001388.jpg](https://github.com/user-attachments/assets/ad4478e4-f71a-4728-9e20-1b36875d16c9)

(also it's showing more/less every time I boot)

**Comment by qzed** [comment] 2024-08-17 23:25
It references [`ipu6_buttress_isr`](https://elixir.bootlin.com/linux/v6.10.5/C/ident/ipu6_buttress_isr), which is part of the `intel-ipu6` module. So your blacklist is not working for some reason.

**Comment by wtfcxt** [comment] 2024-08-17 23:29
> It references [`ipu6_buttress_isr`](https://elixir.bootlin.com/linux/v6.10.5/C/ident/ipu6_buttress_isr), which is part of the `intel-ipu6` module. So your blacklist is not working for some reason.

Yeah and I just found out why. The modules are actually called `intel_ipu6` and `intel_ipu6_isys`

**Comment by qzed** [comment] 2024-08-17 23:37
According to https://elixir.bootlin.com/linux/v6.10.5/source/drivers/media/pci/intel/ipu6/Makefile#L11 it should be `intel-ipu6`. Any chance you ever installed the ipu6 drivers as external kernel module?

**Comment by wtfcxt** [comment] 2024-08-17 23:40
> According to https://elixir.bootlin.com/linux/v6.10.5/source/drivers/media/pci/intel/ipu6/Makefile#L11 it should be `intel-ipu6`. Any chance you ever installed the ipu6 drivers as external kernel module?

I don't think so since I haven't really messed with kernel modules. I only ever used this Surface for browsing and very light gaming (mostly using snap applications).

**Comment by qzed** [comment] 2024-08-17 23:40
You could maybe check this with `dkms status`.

**Comment by wtfcxt** [comment] 2024-08-17 23:49
> You could maybe check this with `dkms status`.

![IMG_20240818_014911548.jpg](https://github.com/user-attachments/assets/ae430f6b-7fcc-464d-a34c-6d3860b968e9)

dkms isn't even installed on this system..

**Comment by yannick-was-taken** [comment] 2024-08-23 14:30
Can confirm that blacklisting only worked with underscores for me as well (arch linux)
