### ISSUE TITLE
Pen aliasing on 5.5.13

### ISSUE THREAD

**Issue by TBombadil** [linux-surface/linux-surface#145] opened 2020-04-01 18:49 UTC
The pen on Ubuntu 19.10 with kernel 5.5.13-surface behaves very badly w.r.t. to tilt. Movement not parallel to the tilt gets very wiggly. Movement parallel to tilt seems unaffected. Use of pen orthogonal to screen also seems to work well, but it's hard to do consistently.
This does not happen with kernel 4.19, so it is probably due to the difference in IPTS implementation.

- Hardware model: SP5
- Kernel version: 5.5.13-surface
- Distribution: Ubuntu 19.10, GNOME 3, 2x scaling

I used Xournal++ for the example image, but the issue appears in every program. 
The zipped image is svg, for finer details.
[pen-tilt.zip](https://github.com/linux-surface/linux-surface/files/4417022/pen-tilt.zip)
![pen-tilt](https://user-images.githubusercontent.com/1665945/78174154-17e4bf80-7459-11ea-8809-c88a02c71fdf.png)

**Comment by kaiksto** [comment] 2020-04-15 11:23
Same issue on Surface Pro 6 with kernel 5.6.4-surface, and earlier with 5.5.
I haven't had this problem with kernel 5.3.
Strokes parallel to tilt are still affected just overlap themselves, visible with transparent brushes.
'Peaks' occasionally flips to other side giving impression of some kind 'digital interference' or misaligned data offset.

- Hardware model: SP6
- Kernel version: 5.6.4-surface (from pkg repository)
- Distribution: Arch Linux, dwm 6.2, no scaling

scaled up example:
![pen_jitter](https://user-images.githubusercontent.com/1736045/79329648-765d7380-7f18-11ea-9950-3da3c5c19cad.png)

**Comment by qzed** [comment] 2020-04-20 16:31
I can confirm that this is an issue. At the moment we're just relaying the raw data that we get from the actual device to the input subsystem. Looks like there needs to be some input processing.

**Comment by archseer** [comment] 2020-06-01 12:16
Quick note: This will be resolved in the new IPTS implementation once it's ready for use: https://github.com/linux-surface/iptsd/commit/8fd2e10e686a7fb2f4e3649271ce67d5721b35b0

**Comment by archseer** [comment] 2020-08-30 13:41
With the switch to iptsd this shouldn't be a problem anymore

**Closed by archseer** 2020-08-30 13:41 UTC
Labels: A: ipts (new)
