### ISSUE TITLE
Emit SW_TABLET_MODE when folding a Surface Pro Typecover

### ISSUE THREAD

**Issue by PJungkamp** [linux-surface/linux-surface#735] opened 2022-02-08 19:45 UTC
I want the typecover input device to emit a SW_TABLET_MODE event when it (de-)activates itself.

When the typecover is folded back, it's keys and backlight deactivate.
Windows detects this and can activate it's tablet mode.
The SW_TABLET_MODE switch should notify about these kinds of events.
Desktop Environments like GNOME should be able to activate/deactivate e.g. an onscreen keyboard depending on the typecover state.

However, libinput will not receive this event on my machine.
```shell
$ libinput debug-events
``` 
yields nothing when folding.
Therefore, i checked whether any event occures on any of the `Microsoft Surface Typecover UNKNOWN` devices (see `dmesg` output).

Using `evtest` on `/dev/input/event12` and folding the typecover back 3 times, yielded:
```shell
$ evtest /dev/input/event12
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x45e product 0x9c0 version 0x111
Input device name: "Microsoft Surface Type Cover UNKNOWN"
Supported events:
  Event type 0 (EV_SYN)
  Event type 3 (EV_ABS)
    Event code 40 (ABS_MISC)
      Value 8389410
      Min        0
      Max       -1
Properties:
Testing ... (interrupt to exit)
Event: time 1644348474.143756, type 3 (EV_ABS), code 40 (ABS_MISC), value 17826611
Event: time 1644348474.143756, -------------- SYN_REPORT ------------
Event: time 1644348476.267465, type 3 (EV_ABS), code 40 (ABS_MISC), value 9306914
Event: time 1644348476.267465, -------------- SYN_REPORT ------------
Event: time 1644348477.967668, type 3 (EV_ABS), code 40 (ABS_MISC), value 16253747
Event: time 1644348477.967668, -------------- SYN_REPORT ------------
Event: time 1644348480.068634, type 3 (EV_ABS), code 40 (ABS_MISC), value 9175842
Event: time 1644348480.068634, -------------- SYN_REPORT ------------
Event: time 1644348481.371321, type 3 (EV_ABS), code 40 (ABS_MISC), value 18481971
Event: time 1644348481.371321, -------------- SYN_REPORT ------------
Event: time 1644348483.472275, type 3 (EV_ABS), code 40 (ABS_MISC), value 10355490
Event: time 1644348483.472275, -------------- SYN_REPORT ------------
```
It seems like the functionality is present but being misreported on.

I'd like to tinker with this myself, but I don't quite know where to start.
E.g. where are event capabilities advertised?

### Environment

- Hardware model: Surface Pro 5 (2017) with Typecover
- Kernel version: `5.16.5-arch1-1-surface`
- Distribution: Arch Linux

<details><summary>`dmesg` output on usb input initialization</summary>

```
[    0.895113] xhci_hcd 0000:00:14.0: xHCI Host Controller
[    0.895126] xhci_hcd 0000:00:14.0: new USB bus registered, assigned bus number 1
[    0.896285] xhci_hcd 0000:00:14.0: hcc params 0x200077c1 hci version 0x100 quirk
s 0x0000000081109810
[    0.898780] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDe
vice= 5.16
[    0.898786] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.898790] usb usb1: Product: xHCI Host Controller
[    0.898792] usb usb1: Manufacturer: Linux 5.16.5-arch1-1-surface xhci-hcd
[    0.898794] usb usb1: SerialNumber: 0000:00:14.0
[    0.899033] hub 1-0:1.0: USB hub found
[    0.899065] hub 1-0:1.0: 12 ports detected
[    0.902729] xhci_hcd 0000:00:14.0: xHCI Host Controller
[    0.902750] xhci_hcd 0000:00:14.0: new USB bus registered, assigned bus number 2
[    0.902755] xhci_hcd 0000:00:14.0: Host supports USB 3.0 SuperSpeed
[    0.902839] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDe
vice= 5.16
[    0.902843] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.902846] usb usb2: Product: xHCI Host Controller
[    0.902848] usb usb2: Manufacturer: Linux 5.16.5-arch1-1-surface xhci-hcd
[    0.902849] usb usb2: SerialNumber: 0000:00:14.0
[    0.902965] hub 2-0:1.0: USB hub found
[    0.902987] hub 2-0:1.0: 6 ports detected
[    1.061635] random: fast init done
[    1.087170] PM: Image not found (code -22)
[    1.149569] usb 1-7: new full-speed USB device number 2 using xhci_hcd
[    1.291595] usb 1-7: New USB device found, idVendor=045e, idProduct=09c0, bcdDevice= 0.07
[    1.291607] usb 1-7: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    1.291612] usb 1-7: Product: Surface Type Cover
[    1.291616] usb 1-7: Manufacturer: Microsoft
[    1.313948] input: Microsoft Surface Type Cover Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input1
[    1.370127] input: Microsoft Surface Type Cover Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input2
[    1.370333] input: Microsoft Surface Type Cover as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input3
[    1.370481] input: Microsoft Surface Type Cover Touchpad as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input4
[    1.370619] input: Microsoft Surface Type Cover as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input5
[    1.370759] input: Microsoft Surface Type Cover as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input6
[    1.370910] input: Microsoft Surface Type Cover as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input7
[    1.371195] hid-generic 0003:045E:09C0.0001: input,hiddev96,hidraw0: USB HID v1.11 Keyboard [Microsoft Surface Type Cover] on usb-0000:00:14.0-7/input0
[    1.371292] usbcore: registered new interface driver usbhid
[    1.371295] usbhid: USB HID core driver
[    1.413292] usb 2-4: new SuperSpeed USB device number 2 using xhci_hcd
[    1.476620] usb 2-4: New USB device found, idVendor=045e, idProduct=0306, bcdDevice= 2.06
[    1.476634] usb 2-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    1.476639] usb 2-4: Product: USB3.0 Card Reader
[    1.476644] usb 2-4: Manufacturer: Realtek
[    1.476648] usb 2-4: SerialNumber: 201209010309
[    1.504333] usb-storage 2-4:1.0: USB Mass Storage device detected
[    1.504964] scsi host0: usb-storage 2-4:1.0
[    1.505281] usbcore: registered new interface driver usb-storage
[    1.505908] tsc: Refined TSC clocksource calibration: 1608.000 MHz
[    1.505923] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x172daa3a18b, max_idle_ns: 440795212390 ns
[    1.505959] clocksource: Switched to clocksource tsc
[    1.517423] usbcore: registered new interface driver uas
[    1.696832] input: Microsoft Surface Type Cover Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input9
[    1.753438] input: Microsoft Surface Type Cover Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input10
[    1.753776] input: Microsoft Surface Type Cover Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input11
[    1.754113] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input12
[    1.754369] input: Microsoft Surface Type Cover Touchpad as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input13
[    1.754597] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input14
[    1.754841] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input15
[    1.755011] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input16
[    1.755150] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input17
[    1.755287] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input18
[    1.755422] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input19
[    1.755556] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input20
[    1.755685] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input21
[    1.755841] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input22
[    1.756031] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input23
[    1.756161] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input24
[    1.756288] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input25
[    1.756426] input: Microsoft Surface Type Cover UNKNOWN as /devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:09C0.0001/input/input26
[    1.756724] hid-multitouch 0003:045E:09C0.0001: input,hiddev96,hidraw0: USB HID v1.11 Keyboard [Microsoft Surface Type Cover] on usb-0000:00:14.0-7/input0
```

</details>

**Comment by PJungkamp** [comment] 2022-02-09 19:31
I read about the [Linux HID drivers](https://www.kernel.org/doc/html/latest/hid/hid-transport.html) and figured out that the `hid_multitouch` driver is responsible for creating the `UNKOWN` input devices. It seems like it claims all reported HID fields of the typecover, which leads to the kernel creating the input devices, despite only handling touch events. See:
https://github.com/linux-surface/kernel/blob/79c1f0e58b463796983080bb5b6087ff16891163/drivers/hid/hid-multitouch.c#L399-L408
https://github.com/linux-surface/kernel/blob/79c1f0e58b463796983080bb5b6087ff16891163/drivers/hid/hid-multitouch.c#L1345-L1362

As far as I currently understand it, I need to write or modify an hid module that claims the vendor specific HID usage for the tablet mode switch and advertises and emits the correct SW_TABLET_MODE input events.
I extracted and decoded the HID report descriptor of the typecover but I didn't figure out which usage corresponds to the switch I am interested in.

How could I go about implementing/testing the driver/device?
Can someone provide guidance or tips on where I should start reading?
I haven't modified a Linux kernel myself yet (I think I only configured and built one using buildroot once).

[type_cover_report_descriptor.txt](https://github.com/linux-surface/linux-surface/files/8035585/type_cover_report_descriptor.txt)

**Comment by qzed** [comment] 2022-02-09 20:13
Copying what I wrote in Matrix for completeness:

> All typecovers except the latest ones (Pro X and Pro 8) are more or less generic USB/HID devices. AFAIK there is no generic HID code for the tablet mode switch, so it seems that Microsoft is using some custom code. So you'd have to figure out which one and then we can translate it with some HID driver.

and from @jonas2515 

> I tried to figure this out at some point when I looked into the communication with the keyboard that disables/enables the backlight. There was a specific sequence being sent when folding it back, but it was a bit different all the time, so I kinda gave up.

So you're on the right track.

I haven't written a (non-transport) HID driver myself yet so I can't really help you with that (but everything you write seems to be correct as far as I can tell). I'd probably start with `hid-recorder` from https://gitlab.freedesktop.org/libevdev/hid-tools and try to figure out the specific report being sent. IIRC the report ID should be the first byte, which you can then use to look up the structure in the descriptor. That should then (hopefully) give you all the info you need for implementing the translation.

**Comment by Biont** [comment] 2022-02-23 19:04
Is this event emitted *at all* currently? This also seems to prevent autorotate from working under Gnome. I'd expect tablet mode to trigger when removing the type cover (SGO3 here), but I feel this is not implemented at al...?

**Comment by jonas2515** [comment] 2022-02-23 19:11
> Is this event emitted at all currently? This also seems to prevent autorotate from working under Gnome. I'd expect tablet mode to trigger when removing the type cover (SGO3 here), but I feel this is not implemented at al...?

Nope, not on surface devices. The whole situation regarding tablet mode is really ugly, GNOME has tried about 3 approaches and heuristics to enable tablet-mode in addition to looking at the kernel event (the kernel is very unreliable here and currently has an allow list for this event because device vendors are as always unreliable, see https://github.com/torvalds/linux/blob/master/drivers/platform/x86/intel/vbtn.c#L204).

Right now what GNOME does is check whether a mouse/touchpad pointer device is attached. So theory tablet mode should be entered even without the kernels tablet mode working. Of course that would break as soon as you plug in a mouse or there's some weird virtual mouse in your setup.

**Comment by qzed** [comment] 2022-02-23 19:13
In addition to @jonas2515: It seems that MS sends a custom HID event (although I'm not sure if this also happens when detaching or just when folding), so someone would need to write a driver translating that. I believe @PJungkamp is working on that, but I don't know the current state. IIRC he has figured out which HID usages/values to look for (maybe that's worth noting down here?), but I don't know any more than that.

**Comment by Biont** [comment] 2022-02-23 19:35
>Of course that would break as soon as you plug in a mouse or there's some weird virtual mouse in your setup.

@jonas2515 I can't believe I simply had to uninstall `ydotool` to make this work. It's certainly not the most sustainable solution, but at least I have a functional tablet now. Thanks a million for clearing this up. I have actually *read* about this check for presence of a pointer in other dcussions, but I really needed your "weird virtual mouse" to realize what's going on.

**Comment by jonas2515** [comment] 2022-02-23 19:43
Ahh yeah, the way it works is definitely a bit unexpected right now, we're trying to this figured out a little bit better in GNOME 42. I proposed [another new heuristic here](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1846#note_1390150), but really getting this completely right would mean getting the kernel (and most likely firmware) fixed on all those devices.

**Comment by PJungkamp** [comment] 2022-02-25 12:43
I was on vacation, but I have some updates and some questions.

What I've just implemented is a patch to the `hid-multitouch` driver which handles the type cover input devices.
I want to advertise an `EV_SW` + `SW_TABLET_MODE` capable input device for the hid usage in question and set the switch state in the event handler.

The HID report descriptor fields in question:
Usage Page/Usage of the Collection: `0xff05/0x05`
Usage of the Folding state: `0x72`
For me this is contained in `Report ID 0x23` of the report descriptor.

The usage reports an 32bit integer although only the lowest byte seems to convey reliable information about the folding state.

The values I got when checking the hid events with `hid-recorder` as @qzed suggested where:
Normal => `(value & 0xFF) == 0x22`
Folded Back => `(value & 0xFF) == 0x33`
Lid Closed => `(value & 0xFF) == 0x13` (disable suspend/hiberante on acpi lid switch to observe this one)

I believe `input_event(field->hidinput->input, EV_SW, SW_TABLET_MODE, (value & 0xFF) == 0x33)` in the `hid-multitouch` driver input event handler should suffice.

It would be great if someone could check this on their own Surface Pro Type Cover!
1. Install `hid-tools` (e.g. from the Arch Linux `community` repository or https://github.com/bentiss/hid-tools)
2. Run `hid-recorder /dev/hidrawX`. You may have multiple of these devices just try each. (this might require root privileges)
3. Look below the report descriptor for a line like: 
```
N: Microsoft Surface Type Cover
I: 3 045e 09c0
```
4. Fold the Type Cover back. `hid-recorder` should report something like:
```
# ReportID: 35 / 0xff050072:    18088755 | 0xff050073:  4272423056 | 0xff050074:     2032785 | 0xff050075:  4269407349 
E: 000000.000000 17 23 33 03 14 01 90 00 a8 fe 91 04 1f 00 75 fc 79 fe
```
5. Fold the Type Cover bak and forth several times to generate some events.
6. Fold the Type Cover back to normal, cancel the command and post the entire output of `hid-recorder` here.

**Comment by PJungkamp** [comment] 2022-02-25 13:09
I think I misinterpreted the data.... It seems like it indicates rotation/orientation and not to folding state.

**Comment by PJungkamp** [comment] 2022-02-25 16:01
I'm trying something like [0013-surface-typecover-tablet-mode.patch.txt](https://github.com/linux-surface/linux-surface/files/8142428/0013-surface-typecover-tablet-mode.patch.txt).

But this is not quite sufficient for a proper EV_SW input device, see https://www.kernel.org/doc/html/latest/input/event-codes.html#ev-sw.
>Upon binding to a device or resuming from suspend, a driver must report the current switch state. This ensures that the device, kernel, and userspace state is in sync.

Reporting the event on suspend should not be a problem, since an `hid_driver` has callbacks for power management events.
But there seems to be no callback from `hid-core` after the input device has been initialized, where I'd set the initial switch state.
See https://github.com/linux-surface/kernel/blob/927cdf72b2586dea911f6c139519b840301aa6e0/include/linux/hid.h#L704-L785.

I don't know yet how to report the switch state "Upon binding to a device [...]".

**Comment by qzed** [comment] 2022-02-25 17:22
I don't really know how to integrate this into the hid-multitouch driver either, but generally you follow the scheme:

```c
// allocate device
input_dev = input_allocate_device();

// set its capabilities (what type of input it provides, seems to be done in mt_touch_input_mapping())
input_set_capability(input_dev, EV_SW, SW_TABLET_MODE);

// get current state
tablet_mode = ...

// report the initial state
input_report_switch(input_dev, SW_TABLET_MODE, tablet_mode);

// register the device
status = input_register_device(input_dev);
```

on resume, you do

```c
// get current state (may have changed during suspend without our knowledge)
tablet_mode = ...

// report it
input_report_switch(input_dev, SW_TABLET_MODE, tablet_mode);
input_sync(input_dev);
```

then for each input you do

```c
input_report_switch(input_dev, SW_TABLET_MODE, tablet_mode);
input_sync(input_dev);
```

The problem is that I don't really know where the `input_allocate_device()` and `input_register_device()` calls are. For testing you can probably skip the suspend/resume and the initialization report (or just fake it in probe with some fixed value). So you should be able to get something working with that. Keep in mind that you do need `input_set_capability()` though.

After that it's a) figuring out where to place the init calls (both `input_set_capability()` and `input_report_switch()`, the other ones seem to be handled by hid-multitouch or some core stuff already) and b) how to query the value. I assume b) can be done via a feature report (IIRC there's a get-report/get-feature-report call in the HID protocol, nut sure about the actual wording).

**Comment by PJungkamp** [comment] 2022-02-25 18:02
I didn't know whether I could report the initial switch state before `input_register_device`!
Then it's easy! The type cover reports the folding state itself after attach and on resume.

I'll report tablet mode off on attach and I'll just repeat the current tablet mode state on resume.
The event handler can then apply the actual state.

With the help of and some more turning my tablet with type cover in any orientation imaginable while looking at the `hid-recorder` output, I'm fairly certain about the meaning of the reported state.

I'll check the lowest byte of the `0x72` usage:
| value | keyboard / backlight | reason |
| --- | --- | --- |
| `0x22` | enabled | / |input_event(field->hidinput->input, EV_SW, SW_TABLET_MODE, (value & 0xFF) == 0x22)
| `0x13` | disabled | lid closed |
| `0x33` | disabled | folded back |
| `0x53` | disabled | right/left side up |
| `0x43` | disabled | folded back and tablet upside down |

Reporting the correct state in the event handler should only be a matter of:
```C
input = field->hidinput->input;
input_event(input, EV_SW, SW_TABLET_MODE, (value & 0xFF) != 0x22);
input_sync(input);
```

**Comment by ostylk** [comment] 2022-02-25 18:11
In my personal attempt to get it working I programmed a small user-space program to emit a SW_TABLET_MODE event via evdev/uinput as I have no experience in kernel programming yet. It is also logging the relevant HID report, so it proved to be really helpful when trying to understand the sent data.

In case you are interested, here is the program's repository: https://dev.ostylk.de/NixDistro/tablet-mode . It works perfectly fine for me, so you can use it till the proper kernel patch comes in.
Note, I never intended for this program to be published (someone convinced me to do so) so I'm sorry for the weird programming language I used.

**Comment by PJungkamp** [comment] 2022-02-25 23:00
I've created a Pull-Request against the surface kernel.

See https://github.com/linux-surface/kernel/pull/119.

**Comment by jonas2515** [comment] 2022-02-26 00:00
Cool stuff and very nice work, looking forward to trying this soon!

Now with that in place, I wonder if we'd also want the kernel to report SW_TABLET_MODE = 1 when there's no type-cover attached, no clue how that might work though. Although I wonder if anyone actually tried adding the Surface to the intel-vbtn driver allowlist (https://github.com/torvalds/linux/blob/master/drivers/platform/x86/intel/vbtn.c#L204), maybe the firmware actually defaults to enabling tablet mode, who knows...

**Comment by PJungkamp** [comment] 2022-02-26 12:38
At least the GNOME heuristic works well with this! (Although I did need to uninstall ydotool for it to work)

How would libinput handle two tablet mode switch input devices? `intel_vbtn` would create an input device which may report information that is in conflict with the switch state reported by `hid_multitouch`.

**Closed** 2022-06-12 18:36 UTC
