### ISSUE TITLE
Installing libwacom-surface removes Gnome and/or XFCE

### ISSUE THREAD

**Issue by jmcturnan** [linux-surface/linux-surface#111] opened 2020-03-05 21:02 UTC
As reported by ftastisch, I can confirm:  

_"Installed libwacom-surface (which removes libwacom with the side effect that Gnome was removed as well)"_  

I went through this twice.  Once on an Arch - Gnome install and a second time on a Manjaro - Gnome install.  Both on the same Surface Book (Gen 1).

Hardware model: Surface Book (Gen 1)
Kernel version: 5.5.6-arch (default kernel)
Distribution: Architect Arch (1st incident),  Manjaro (2nd incident)

_Originally posted by @jmcturnan in https://github.com/linux-surface/linux-surface/issues/110#issuecomment-595443240_

**Comment by ftastisch** [comment] 2020-03-05 22:18
At least I was using pamac, maybe that causes the problem.

**Comment by qzed** [comment] 2020-03-05 23:58
Can you confirm if it's a pamac issue by checking that this works manually via pacman? (install `libwacom` via pacman and make sure that that doesn't remove gnome, then run `git clone https://aur.archlinux.org/libwacom-surface.git`, `cd libwacom-surface`, and `makepkg -fsi`).

**Comment by ftastisch** [comment] 2020-03-06 06:11
> Can you confirm if it's a pamac issue by checking that this works manually via pacman? (install `libwacom` via pacman and make sure that that doesn't remove gnome, then run `git clone https://aur.archlinux.org/libwacom-surface.git`, `cd libwacom-surface`, and `makepkg -fsi`).

Running those commands results in
```
==> Verifying source file signatures with gpg...
    libwacom-1.2.tar.bz2 ... FAILED (unknown public key E23B7E70B467F0BF)
==> ERROR: One or more PGP signatures could not be verified!
```

Installing with yay -S libwacom-surface seems to work as intended.

**Comment by qzed** [comment] 2020-03-06 14:41
You have to import the PGP key to be able to verify the signatures (`gpg --recv-keys E23B7E70B467F0BF`). Most AUR helpers will do that for you automatically (such as yay).

In any case, this looks like a pamac/AUR helper issue.

**Comment by jmcturnan** [comment] 2020-03-06 21:02
> Can you confirm if it's a pamac issue by checking that this works manually via pacman? (install `libwacom` via pacman and make sure that that doesn't remove gnome, then run `git clone https://aur.archlinux.org/libwacom-surface.git`, `cd libwacom-surface`, and `makepkg -fsi`).

Yes -- I was also using pacman.  I'm no longer using Gnome.  Related:  is libwacom-surface only for Gnome?  I think I did read something saying that it was just for Gnome.

**Comment by qzed** [comment] 2020-03-06 22:28
AFAIK only Gnome makes direct use of it. Although on Arch `libinput` also depends on libwacom, so I'm not quite sure.

**Comment by martinnyborg** [comment] 2020-03-08 21:45
I just experienced the same thing, I tried uninstalling libwacom-surface and it wanted to uninstall my Gnome installation.

`yay -R libwacom-surface
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing libwacom-surface breaks dependency 'libwacom' required by gnome-settings-daemon
:: removing libwacom-surface breaks dependency 'libwacom' required by libinput
`

**Comment by qzed** [comment] 2020-03-08 22:41
@martinnyborg That is expected. You need _something_ that provides libwacom to fulfill dependencies on libwacom. Either the `libwacom-surface` or the `libwacom` package. You cannot remove it (without removing anything that depends on it), you rather have to replace it. So if you want to replace `libwacom-surface` with `libwacom` you have to install `libwacom`, which will automatically do that.

**Comment by archseer** [comment] 2020-03-09 02:30
I'm closing this as it's not something we can address here, `pacman` works as intended. I recommend opening an upstream issue with [pamac](https://gitlab.manjaro.org/applications/pamac). (That said, I don't like that they reimplemented dependency resolution. Surely there's a way to integrate pamac with pacman directly)

**Closed by archseer** 2020-03-09 02:30 UTC
