### ISSUE TITLE
[SP7] Bluetooth not working

### ISSUE THREAD

**Issue by Crashdummyy** [linux-surface/linux-surface#1594] opened 2024-10-23 13:02 UTC
### Description

I did a clean installation of Fedora40 yesterday and everything appears to work as expected.
The only thing that refuses to work appears to be bluetooth.

Theres nothing suspicious in the dmesg or journal besides every attempt being refused.
`Failed to set mode: Busy (0x0a)`

### Environment
- Hardware model: Surface Pro 7
- Kernel version: `6.11.4-1.surface.fc40.x86_64`
- Distribution: `Fedora Linux 40 (Workstation Edition)`

#### dmesg output

[Link due to Github 65536 character limit reached](https://paste.systemli.org/?a8739e7dc55b50c0#89upzHcrgrHR8JBSMBZ7ZWxFze2bwkXUkp8BW6zYf77M)
</details>

**Comment by lcyf9102s** [comment] 2024-10-23 16:46
Similar on Arch, Bluetooth can't find any devices. Seems that it is caused by the new kernel update. Roll back to 6.10.10 and Bluetooth works fine.

**Comment by GarrettRobinson** [comment] 2024-10-25 15:34
Same issue on Surface Laptop Studio 1 on Arch - resolved by 6.11.5 kernel

**Comment by YuHadoko** [comment] 2024-10-28 08:44
what if i first installed fedora40 with 6.11.4 kernel?

**Comment by feakuru** [comment] 2024-10-31 00:04
not resolved for me on SP7

**Comment by a-aye-ron** [comment] 2024-11-06 20:55
I will also verify running Fedora 40 on a Suface Book 3 that kernel 6.11.4-1.surface.fc40.x86_64 has broken bluetooth functionality and that it was necessary to downgrade to kernel 6.10.10-1.surface.fc40.x86_64.

Specifically, 6.11.4-1.surface.fc40.x86_64 wasn't able to pair bluetooth devices. After downgrading the kernel, I was able to pair, and they eventually appeared to function on the latest kernel. However, after using the latest kernel more extensively, I noticed that bluetooth would stop working after some time, specifically when resuming from suspend.

**Comment by feakuru** [comment] 2024-11-27 11:31
> Is this a duplicate of https://github.com/linux-surface/linux-surface/issues/1603 ?

Looks like much the same logs, but this issue is the one where I found mention of Arch, and I should specify that for me as well, the problem appears on Arch. Should the fedora upstream merge fix things for Arch as well?

**Comment by qzed** [comment] 2024-12-10 19:27
New releases should be out later today. Hopefully those fix that.

**Comment by feakuru** [comment] 2024-12-11 10:28
Bluetooth seems to work now with the latest update, thanks qzed!

**Closed as completed** 2024-12-11 12:58 UTC

**Comment by simdeistud** [comment] 2025-01-31 16:53
If this bug has been fixed, then the [support matrix's](https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features) point n.15 should be removed/edited

**Comment by Selkous** [comment] 2025-03-07 19:53
It works on surface pro 4, kernel 6.12.7-1.
