### ISSUE TITLE
Typecover not reinitialized on reconnect

### ISSUE THREAD

**Issue by Cyborgscode** [linux-surface/linux-surface#119] opened 2020-03-10 19:36 UTC
Kernel:  5.5.8-1.surface.fc30.x86_64
Device: SP4

if the typecover is removed and reattached, it does not start to work again.

Symptoms:

- dmesg is silent
- lsusb finds the typecover after reconnect 
- removing and reload ipts kernel mod is not helping
- journald does not log removal or reattachment of the typecover
- mod usbhid which drives the typecover is build in and therefor cant be reloaded.

**Comment by archseer** [comment] 2020-03-14 00:47
See https://github.com/linux-surface/linux-surface/issues/105

There was a workaround in the wiki that was said to not be needed anymore. If that fixes your issue I'll restore the wiki page

**Comment by Cyborgscode** [comment] 2020-03-14 08:52
workaround NOT WORKING .. 
modreload issued via ssh : NOT WORKING

Problem caused by: NOT DETECTING the remove of the usb device
Proof:
# lsusb
Bus 002 Device 002: ID 045e:090c Microsoft Corp. SD Card
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 045e:09c0 Microsoft Corp. Surface Type Cover
Bus 001 Device 003: ID 1286:204c Marvell Semiconductor, Inc. Bluetooth and Wireless LAN Composite Device
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

But the typecover is physically removed. 

DMESG is not reporting the dis- or reattachment of the typecover.

**Comment by Cyborgscode** [comment] 2020-03-14 08:58
Seems to be an upstream Bug in 5.5.8 : fedora 5.5.8-100 kernel does behave the same.
(notice: due to the lack of touch support in upstream kernel, device gets rendered useless by this, so don't try at home kids :) )

**Comment by Cyborgscode** [comment] 2020-03-14 09:03
Confirmed: Upstream Bug in 5.5.x 
kernel 5.4.19 works as expected.

**Comment by Cyborgscode** [comment] 2020-03-14 09:22
Reference for tracking: RH BZ#1813530

**Comment by Cyborgscode** [comment] 2020-03-14 10:37
Fixed in 5.5.9-2

**Comment by Cyborgscode** [comment] 2020-03-14 10:49
Reopen: Not fixed in 5.5.9-2

**Comment by Cyborgscode** [comment] 2020-03-14 10:50
First kernel boot , usb was working as it should .
two Reboots later, did not work anymore.

**Comment by Cyborgscode** [comment] 2020-03-14 12:10
update: Bug confirmed for 5.5.9-200.fc31

**Comment by kitakar5525** [comment] 2020-03-14 13:49
Yes, I can confirm this issue on SB1 and Surface 3 (non-pro). `sudo modprobe -r usbhid; sudo modprobe usbhid` from SSH helped.

From my observation, it seems that this issue will happen when keyboard is auto-suspended.

Debug output for usbhid (auto-suspend state will be printed to dmesg):
```bash
echo "file drivers/hid/usbhid/* +p" | sudo tee /sys/kernel/debug/dynamic_debug/control
```

**Comment by kitakar5525** [comment] 2020-03-14 13:58
So, steps to reproduce:
1. set auto-suspend enabled for keyboard
   For example, on powertop, search for `Autosuspend for USB device Surface Keyboard [Microsoft]` and toggle it to `Good`
2. enable debug output for auto-suspend: `echo "file drivers/hid/usbhid/* +p" | sudo tee /sys/kernel/debug/dynamic_debug/control`
3. wait until the keyboard goes into auto-suspend: (`usbhid 1-1.4:1.0: suspend` or like will be printed to dmesg)
4. detach the keyboard
5. re-attach the keyboard

Result:
Keyboard will be unusable until I reload `usbhid`: `sudo modprobe -r usbhid; sudo modprobe usbhid`

**Comment by Cyborgscode** [comment] 2020-03-14 15:15
PRO4: 5.5.9-2  
First Try: WLAN disconnected after sys/kernel change ..  hard reboot
Second Try: Suspend came...
modprobe -r usbhid; modprobe usbhid 
modprobe: FATAL: Module usbhid is builtin.

there are only BT modules or the UAS module ( massstorage via usb). 


You must use a different distribution.. 

# lsmod |grep hid
i2c_hid                32768  0
hid_sensor_als         20480  1
hid_sensor_gyro_3d     20480  0
hid_sensor_rotation    20480  0
hid_sensor_accel_3d    20480  1
hid_sensor_trigger     20480  8 hid_sensor_gyro_3d,hid_sensor_als,hid_sensor_accel_3d,hid_sensor_rotation
hid_sensor_iio_common    20480  5 hid_sensor_gyro_3d,hid_sensor_trigger,hid_sensor_als,hid_sensor_accel_3d,hid_sensor_rotation
industrialio_triggered_buffer    16384  4 hid_sensor_gyro_3d,hid_sensor_als,hid_sensor_accel_3d,hid_sensor_rotation
industrialio           94208  9 industrialio_triggered_buffer,hid_sensor_gyro_3d,hid_sensor_trigger,kfifo_buf,hid_sensor_als,hid_sensor_accel_3d,hid_sensor_rotation
hid_sensor_hub         24576  6 hid_sensor_gyro_3d,hid_sensor_trigger,hid_sensor_iio_common,hid_sensor_als,hid_sensor_accel_3d,hid_sensor_rotation
hid_multitouch         32768  0

**Comment by kitakar5525** [comment] 2020-03-15 14:46
@Cyborgscode It seems that `usbhid` driver is built-in on Fedora. I use Arch Linux and the driver is built as module.

I guess autosuspend for your Type Cover is enabled. Whats's the state after reboot?
```bash
# Print autosuspend state for all USB devices
grep . /sys/bus/usb/devices/*/{product,power/control}
```

`auto` means "allowed to autosuspend" and 'on' means "autosuspend is not allowed" (https://www.kernel.org/doc/html/latest/driver-api/usb/power-management.html#the-user-interface-for-dynamic-pm)

If enabled, you can disable autosuspend by writing `on` to `power/control` and can you check this issue doesn't happen anymore?

**Comment by kitakar5525** [comment] 2020-03-15 14:49
Forgot to mention, reloading `i2c_hid` did not fix this issue. So, it might be a different issue from #105 (By the way, why reloading `i2c_hid` helped for #105?)

**Comment by Cyborgscode** [comment] 2020-03-29 15:18
Bug confirmed for 5.5.10.fc30 and 5.5.13-1.surface

**Comment by kitakar5525** [comment] 2020-05-14 12:11
I tried Arch Linux 5.4 LTS before and 5.4.22 is not affected but exactly after 5.4.23 is affected regarding 5.4 series.

I saw a comment on [Red Hat Bugzilla – Bug 1813530](https://bugzilla.redhat.com/show_bug.cgi?id=1813530#c22) that the issue is fixed. So, I tried myself now and I can confirm that this issue [1] is fixed exactly after upstream 5.6.8 [2] regarding 5.6 series.

[1] I mean "keyboard not working after reattaching if keyboard was autosuspended on detaching"
[2] on that bugzilla, reported that "5.6.7 seems to have fixed" but for me I'm sure that upstream 5.6.7 is still affected but fixed on 5.6.8

**Comment by kitakar5525** [comment] 2020-05-14 12:12
If I assume that this issue has been appeared on 5.4.23 and fixed on 5.6.8, the candidate related commits are:
- issue introduced by commit
  https://github.com/torvalds/linux/commit/8099f58f1ecddf4f374f4828a3dff8397c7cbd74
  ("USB: hub: Don't record a connect-change event during reset-resume")
- and fixed by commit
  https://github.com/torvalds/linux/commit/9f952e26295d977dbfc6fedeaf8c4f112c818d37
  ("USB: hub: Fix handling of connect changes during sleep")

Those commits were backported to older kernels. So, the related versions regarding 4.19, 5.4, and 5.6 series are the following:
- affected after v4.19.107, v5.4.23, and v5.6-rc3
- fixed after v4.19.119, v5.4.36, and v5.6.8

**Comment by kitakar5525** [comment] 2020-05-14 12:13
@Cyborgscode 
So, can you also try on the latest linux-surface kernel?

**Comment by Cyborgscode** [comment] 2020-05-14 12:22
5.6.11-1 : *Fix Confirmed*

**Comment by kitakar5525** [comment] 2020-05-14 12:32
OK, thank you for confirming! Closing this issue as fixed by upstream.
Feel free to reopen this issue if issue still persists.

**Closed by kitakar5525** 2020-05-14 12:32 UTC
Labels: A: typecover, C: bug (upstream), D: Surface Pro 4
