### ISSUE TITLE
WiFi 802.11r appears to be broken

### ISSUE THREAD

**Issue by Frans-Willem** [linux-surface/linux-surface#386] opened 2021-01-16 16:57 UTC
My surface is unable to connect to WiFi networks using 802.11r fast transition, it just keeps asking for the password.
Only when I manually recompile wpa_supplicant with the CONFIG_IEEE80211R=y line commented out in the config, am I allowed to join the network.
All other devices (phones, windows laptops, etc) have no trouble joining this network.

### Environment

- Hardware model: Surface Pro 6
- Kernel version: 5.10.1
- Distribution: Arch Linux

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

```

</details>

**Comment by Frans-Willem** [comment] 2021-01-16 17:05
This appears to be the same issue, posted 10 months ago also on a Surface Pro 6 with kernel 5.5.11. Github username appears to be @hadallen

https://www.reddit.com/r/linux4noobs/comments/foipcm/networkmanager_no_wifi_connection_arch_linux/

**Comment by hadallen** [comment] 2021-01-16 17:54
hello, 

I wish I had a solution for this issue. Some wifi networks don't work with NetworkManager on my surface, but most do. I switch to using netctl for some networks when I need to. I'm sorry I can't assist further on this. I have let my surface fall behind lately as I've been busy with school and using my desktop mostly lately.

**Comment by jonas2515** [comment] 2021-04-03 08:16
Sounds like that's broken in mwifiex or in the wifi firmware. I don't have an AP that supports this so I can't test it right now, I guess for now we can try to disable the feature.

**Comment by jonas2515** [comment] 2021-04-04 08:48
Can you share the output of `iw dev wlp1s0 scan` for the network it doesn't work with?

**Comment by hadallen** [comment] 2021-04-04 14:14
hello, unfortunately I dont have the same issue at home anymore as I upgraded my modem from my ISP and then got a new router since the provided one was getting more and more restrictive with the settings. I no longer have the issue at home, but I think it still happens when I am at my in-laws house. Next time I am there I can try to gather some info

**Comment by jonas2515** [comment] 2021-04-23 12:46
I think I've been able to reproduce this one now by creating an AP that offers WPA-PSK and FT-PSK with hostapd. Hostapd (so the AP) reports AP-STA-POSSIBLE-PSK-MISSMATCH when the connection fails.

Luckily, that bug goes away when switching to wpa_supplicant from master on the station, so this likely was a wpa_supplicant bug. Other than that, NetworkManager and wpa_supplicant appear to be handling it just fine, using WPA-PSK because our card doesn't support FT-PSK (just the same as on Windows btw).

I'm closing this issue now, please update to the newest release of wpa_supplicant, and if the issue continues to happen please reopen.

**Closed by jonas2515** 2021-04-23 12:46 UTC
Labels: A: mwifiex
