### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by hanskokx** [linux-surface/linux-surface#475] opened 2021-06-21 19:59 UTC
Webcam support

### Environment
Linux NeonBook 5.12.10-surface #1 SMP Sun Jun 13 21:19:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```
❯ sudo ninja -C build install
ninja: Entering directory `build'
[1/2] Installing files.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 514, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 330, in do_install
    d = pickle.load(ifile)
AttributeError: Can't get attribute 'OctalInt' on <module 'mesonbuild.coredata' from '/usr/lib/python3/dist-packages/mesonbuild/coredata.py'>
FAILED: meson-install 
/home/hans/.local/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

</details>

**Comment by SamLukeYes** [comment] 2021-06-22 14:39
Which distro are you using? And which version of meson does your distro provide?

**Comment by hanskokx** [comment] 2021-06-23 16:40
❯ meson --version

0.58.1
❯ cat /etc/issue
KDE neon 5.22 \n \l

**Comment by SamLukeYes** [comment] 2021-06-24 01:15
As far as I know, KDE neon is based on the latest Ubuntu LTS (currently 20.04), which provides meson 0.53.2 in their official repo. Have you installed meson 0.58.1 in your user directory alongside with 0.53.2 system-wide? It might cause this issue using meson 0.58.1 to build and 0.53.2 to install.

**Comment by hanskokx** [comment] 2021-06-24 01:23
That does not appear to be the case:

❯ /home/hans/.local/bin/meson --version
0.58.1
❯ /usr/bin/meson --version
0.58.1
❯ which meson
/home/hans/.local/bin/meson

**Comment by hanskokx** [comment] 2021-06-24 01:24
I wonder if this is relevant?

❯ history|grep meson
1172 sudo apt install \\n build-essential meson ninja-build pkg-config libgnutls28-dev openssl \\n pyt
hon3-pip python3-yaml python3-ply python3-jinja2 \\n qtbase5-dev libqt5core5a libqt5gui5 libqt5widgets5 qtt
ools5-dev-tools \\n libtiff-dev libevent-dev \\n clang libc++-dev libc++abi-dev\n
1173 pip3 install --user meson
1174 pip install --user meson
1175 pip3 install --user meson
1176 pip3 install --user --upgrade meson
1178 CC=clang CXX=clang++ meson build -Dpipelines=uvcvideo,ipu3 -Dprefix=/usr

**Comment by SamLukeYes** [comment] 2021-06-24 02:10
There's a similar issue https://github.com/mesonbuild/meson/issues/8695 here, but the author closed it without further explanation :confused:

**Comment by hanskokx** [comment] 2021-06-24 02:30
😖

**Comment by headkaze** [comment] 2021-06-24 17:44
This is what I had to do to get it compiling. After following the instructions [here](https://github.com/linux-surface/linux-surface/wiki/Camera-Support#libcamera-support) I ran the following:

```
pip3 uninstall meson
CC=clang CXX=clang++ meson build -Dpipelines=uvcvideo,ipu3 -Dprefix=/usr
ninja -C build
sudo ninja -C build install
sudo chown -R $USER:$USER build
```

The last line is required to build again because some files in the build directory get root ownership.

I'm not saying any of this is correct only that it's what seemed to get it compiling for me.

**Comment by localjo** [comment] 2021-07-25 18:54
It seems to me that the issue is related to installing meson for the user. According to [a comment in this thread](https://github.com/mesonbuild/meson/issues/8425#issuecomment-786371041), "In order to use sudo ninja install, meson must be installed as root". 

Uninstalling the user meson with `pip3 uninstall meson` and using the system one instead worked. I had to remove the `build` directory and rebuild before installing.

**Closed** 2022-04-11 01:22 UTC
Labels: C: misc, A: cameras
