### ISSUE TITLE
Installing libwacom-surface on Ubuntu 22.04 removes gnome desktop

### ISSUE THREAD

**Issue by mitchy93** [linux-surface/linux-surface#799] opened 2022-04-25 04:22 UTC
**installing the libwacom-surface package on ubuntu 22.04 removes gnome desktop packages and breaks gnome, not installing this package stops this issue from happening**

- Hardware model: surface go version 1
- Kernel version: 5.15.0-25-generic
- Distribution: Ubuntu 22.04 - Gnome 42

**apt output:**

mitch@mitch-Surface-Go:~$ sudo apt install linux-image-surface linux-headers-surface iptsd libwacom-surface
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  apg cheese-common gir1.2-accountsservice-1.0 gir1.2-adw-1 gir1.2-gck-1
  gir1.2-gcr-3 gir1.2-gdm-1.0 gir1.2-geoclue-2.0 gir1.2-gnomebluetooth-3.0
  gir1.2-graphene-1.0 gir1.2-gtk-4.0 gir1.2-gweather-3.0 gir1.2-json-1.0
  gir1.2-nm-1.0 gir1.2-nma-1.0 gir1.2-rsvg-2.0 gir1.2-upowerglib-1.0
  gkbd-capplet gnome-bluetooth-3-common gnome-control-center-faces
  gnome-online-accounts gnome-shell-common gnome-video-effects
  gstreamer1.0-pipewire libclutter-1.0-common libcogl-common libcogl-pango20
  libcogl-path20 libcogl20 libcolord-gtk1 libfreerdp-server2-2 libgdm1
  libgnome-bluetooth-3.0-13 libgnomekbd-common libgnomekbd8
  libgoa-backend-1.0-1 libgsound0 libgssdp-1.2-0 libgupnp-1.2-1
  libgupnp-av-1.0-3 libgupnp-dlna-2.0-4 libmtdev1 libpulse-mainloop-glib0
  librygel-core-2.6-2 librygel-db-2.6-2 librygel-renderer-2.6-2
  librygel-server-2.6-2 libsysmetrics1 libvncserver1 libxcb-res0
  libxkbcommon-x11-0 libxklavier16 mobile-broadband-provider-info
  mutter-common network-manager-gnome power-profiles-daemon python3-certifi
  python3-macaroonbakery python3-protobuf python3-pymacaroons python3-requests
  python3-rfc3339 python3-tz rygel switcheroo-control xwayland
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  linux-headers-5.16.17-surface linux-image-5.16.17-surface
  notification-daemon policykit-1-gnome
The following packages will be REMOVED:
  cheese gdm3 gir1.2-mutter-10 gnome-control-center gnome-initial-setup
  gnome-remote-desktop gnome-settings-daemon gnome-shell
  gnome-shell-extension-appindicator gnome-shell-extension-desktop-icons-ng
  gnome-shell-extension-ubuntu-dock gstreamer1.0-clutter-3.0 libcheese-gtk25
  libcheese8 libclutter-1.0-0 libclutter-gst-3.0-0 libclutter-gtk-1.0-0
  libinput-bin libinput10 libmutter-10-0 libwacom-bin libwacom-common
  libwacom9 ubuntu-desktop ubuntu-desktop-minimal ubuntu-session
  xserver-xorg-input-all xserver-xorg-input-libinput
The following NEW packages will be installed:
  iptsd libwacom-surface linux-headers-5.16.17-surface linux-headers-surface
  linux-image-5.16.17-surface linux-image-surface notification-daemon
  policykit-1-gnome
0 to upgrade, 8 to newly install, 28 to remove and 0 not to upgrade.
Need to get 77.7 MB of archives.
After this operation, 355 MB of additional disk space will be used.

**Comment by RichardODonoghue** [comment] 2022-04-25 11:58
Can confirm I have had the same issue today with my surface laptop 4. I'm not able to reinstall it either...

**Comment by florianschndlr** [comment] 2022-04-26 10:23
Encountered the same issue on my SB2.

**Comment by qzed** [comment] 2022-04-27 15:18
Closing as duplicate of #783.

**Closed by qzed** 2022-04-27 15:18 UTC
