### ISSUE TITLE
How to install Nvidia (and recommended way)?

### ISSUE THREAD

**Issue by mmalmeida** [linux-surface/linux-surface#46] opened 2020-01-14 16:02 UTC
While installing Ubuntu 18.04 on SB2, I have become rather stuck when installing NVidia Drivers for dedicated support.

Trying to find the best approach (and if successful, I can update https://github.com/linux-surface/linux-surface/wiki/Surface-Book-2 accordingly).

**Q1: Where is Nvidia card?**
I've tried a few commands, but none finds me a reference to Nvidia:
-  ubuntu-drivers devices: none fo
- lshw -c display: only UHD Graphics 620 found
- lspci -k: no reference to Nvidia found

Does one need to install anything else after the kernel 5.3.18 to have nvidia detected? (see https://docs.google.com/spreadsheets/d/1MQZKxZZWc9Kp3Nnag7Qc3UJ-S5AQQ_sw6-2CuzawnQQ/edit#gid=0&range=Q10 for reference of what was installed).

**Recommended way to install**
**Q2:** Is the recommended way to install following:
- https://turlucode.com/how-to-install-ubuntu-18-04-on-surface-book-2/ +

i.e. 
1. installing the drivers via the ppa:graphics-drivers/ppa repository
2. Follow the "NVIDIA Optimus + bbswitch" at  https://turlucode.com/optimus-bbswitch-on-ubuntu-18-04/ to blacklist the nvidia and set the intel as default

**Q3:** Should one update DTX daemon to unload nvidia when undocking? Tthis break anything running with the nvidia card at that time, correct?

**Q4:** **Status**
@qzed you mention in https://github.com/linux-surface/linux-surface/issues/36#issuecomment-571993654 "dGPU is the sub-par performance when not connected to AC" - does this still apply?

**Comment by qzed** [comment] 2020-01-14 21:07
1. The dGPU is (completely) powered off by default during boot. Specifically when `surface_sam_hps` (the driver for dGPU hot-plugging and power-control) loads. To turn it on you can use the [`surface`](https://github.com/linux-surface/surface-control) command line tool by running `surface dgpu set on`. For more details see the [SAM readme](https://github.com/linux-surface/surface-aggregator-module#controlling-the-dgpu-power-state). After that it should show up in `lspci`.

2. I'm not too sure how Ubuntu handles that, but you will need to install a DKMS version, meaning that the nvidia driver needs to be (partly) compiled specifically for the custom kernel you're using. Apart from that, I concur that optimus is the way to go (bbswitch isn't strictly necessary here). At the moment, you will still need to turn on the dGPU manually, using e.g. the `surface` tool, before you can run anything via `optirun` (and off afterwards). There is experimental support for vgaswitcheroo, which allows `optirun` to do that automatically, see https://github.com/linux-surface/surface-aggregator-module/issues/28#issuecomment-569428503 for details (you'll have to manually install the module for that as that isn't integrated into the kernel yet, if you want to go that route, note that you have to [blacklist all built-in modules](https://github.com/linux-surface/surface-aggregator-module#permanently-install-the-module)).

3. Undocking while any program is using the dGPU will cause that program to crash and (potentially) corrupt the driver state. What you can do is adapt the DTX daemon detach script, in which you can try to unload the nvidia module(s), and if that fails cause the script to return an error code. Unloading the module(s) will fail if any program is using the dGPU and the script returning an error code will not allow the EC to open the latch, basically aborting the detachment process. With that you'll only be able to detach the clipboard if nothing is using the dGPU.

4. That unfortunately still applies. When connected to the AC you'll need to change the [performance modes](https://github.com/linux-surface/surface-aggregator-module#setting-the-performance-mode), but that doesn't seem to have the same effect when not connected to AC.

**Comment by han-so1omon** [comment] 2020-01-24 19:48
I am investigating this so that I can use my dGPU within docker containers. I have found this page:

https://github.com/qzed/linux-surfacebook2-mshw0153/blob/master/README.md#setting-up-the-dgpu-for-use-with-bumblebee-and-the-official-nvidia-driver-on-arch-linux

I am wondering if these instructions for running the dGPU are still valid: i.e. 

```
1) Install the nvidia driver (e.g. nvidia-dkms). Note that, if you have a custom kernel, it is important you choose a locally compiled version (as usually indicated by the -dkms suffix).
2) Install bumblebee.
3) Add your user to the bumblebee group (e.g. usermod -a -G bumblebee <yourusername>).
4) Enable bumblebeed.service (systemctl enable bumblebeed.service). Alternatively, you can also start/stop the service before/after each use.
...
```

As of now I can find my device via `lspci`, but I can't find the nvidia drivers or nvidia.ko folder under `/usr/lib/modules/<kernel-version>/kernel/drivers/video`

**Comment by mmalmeida** [comment] 2020-01-26 18:07
@han-so1omon I tried those instructions last week without luck.
In particular, I believe I was able to execute all 4 steps, but ran an error when I then tried to run a program via optitun (optitun glxgears). If memory doesn't fail me, it mentioned it could not find nvidia driver or something like that (even though I had nvidia-dkms).

Have you tried it?

**Comment by qzed** [comment] 2020-01-26 19:44
@han-so1omon Those instructions should still be valid. If you want to run it within a docker container, I don't think you'll need bumblebee/optirun. That is only required if you want to offload graphics applications.

Given your description, this looks like an installation issue (you're using the `dkms` version of the nvidia driver, right?).

Regarding nouveau: I've had trouble to get that driver working without some warning messages in the first place. So I'm not sure if it's fully functional. Apart from that you'll likely have worse performance than with the proprietary one.

**Comment by qzed** [comment] 2020-01-26 19:46
@mmalmeida The best way to check if the dGPU is working is via `nvidia-smi`. All you have to do for that is turn on the dGPU. `nvidia-smi` should load the drivers automatically.

**Comment by han-so1omon** [comment] 2020-01-27 22:26
@mmalmeida I tried the instructions. I installed the drivers from the nvidia-beta-dkms user-contributed repo on Arch linux. Other branches are not available with the dkms option. Bumblebeed service was not able to start, as it required a non-existent bbswitch module. I did not install bbswitch because I think there is another mechanism for doing dGPU switching.

I can see through nvidia-smi that certain X-org windows are controlled through the GeForce 1060 graphics card, but I don't think my docker containers were using the nvidia card, as nvidia-smi is only showing <10MB in use.

What would be really useful for me is a version of the nvidia driver that includes opencl compatibility, but that is out of the scope of this thread.

**Comment by qzed** [comment] 2020-01-27 23:36
@han-so1omon As mentioned, if you want to only run stuff in docker, you don't need bumblebee. If you want to use bumblebee, you can either configure it to not use bbswitch (eg. by not using PM control at all, which I recommend for the time being) or install the bbswitch module (with which automatic PM control still doesn't work but the warning should be gone).

Getting the card set up in docker is probably a docker config issue and requires tweaking on that end. If `nvidia-smi` works, it should behave just like a normal secondary GPU.

If you're on Arch and want opencl compatibilit you need to install `opencl-nvidia` in addition (if that doesn't work with `nvidia-beta-dkms`, there's also `opencl-nvidia-beta`). Also plain `nvidia-dkms` should also be available, not only the beta version.

**Comment by han-so1omon** [comment] 2020-01-28 05:26
Thanks. I thought OpenCL support would be built into the kernel module.
@mmalmeida the method in the link above works for me. After changing /etc/bumblebee/bumbleebee.conf line `PMMethod=auto` to `PMMethod=none` and also installing opencl-nvidia-beta I have bumblebee and OpenCL suport as well. I did not run into the error finding the nvidia driver. Perhaps you could post the error.

**Comment by qzed** [comment] 2020-01-28 12:25
@han-so1omon The device-in-use issue could be an annoying habit by Gnome (maybe also happens on other distros) that "claim" the device even if they're not using it. You can try to track those users down via `lsmod | grep nvidia` and `lsof <path>` where `<path>` is anything under `/dev` with `nvidia` in its name and probably also `/dev/dri/cardX` and `/dev/dri/renderX` where `X` means the one associated with the device.

To avoid that I've disabled the dGPU by default on start-up as that's when this thing happens. If it's turned on while Gnome is running it shouldn't get claimed by it (launching a new Gnome session will also cause that). No idea how KDE behaves, so things might be different there. I unfortunately haven't found a good solution for that other than disabling the dGPU by start-up.

**Comment by qzed** [comment] 2020-01-28 12:31
@mmalmeida see also https://github.com/linux-surface/linux-surface/issues/62. Basically you need to make sure that the dkms driver installed correctly. In the linked issue the problem is that driver 435.21 does not support version 5.4 kernels and thus refuses to install.

**Comment by qzed** [comment] 2020-04-24 01:41
Closing as there hasn't been any response of late and the question seems answered.

**Closed by qzed** 2020-04-24 01:41 UTC
Labels: A: dGPU, A: sam, C: question, D: Surface Book 2
