### ISSUE TITLE
Spyware

### ISSUE THREAD

**Issue by jumminjummin** [linux-surface/linux-surface#1144] opened 2023-05-24 01:25 UTC
I installed debain on my surface pro with no problems. As soon as I installed the kernel, every time I startup my surface pro, it starts auto connecting to some Fastly.com server in San Francisco. Fuck you. You people are why nobody will ever switch to open source.

**Comment by qzed** [comment] 2023-05-24 01:47
First of all: Language. Second: Do you have any proof for your accusations? Because I would be very interested in that myself. The kernel should definitely not do _any_ random internet connections to whatever websites.

So... did you install any other packages? Can you verify from which application the connection is coming / whether it really is the kernel? Any more details would be helpful.

For the record: All of our sources are public and you can verify everything yourself. For the kernel: Patches are [here](https://github.com/linux-surface/linux-surface/tree/master/patches), the build scripts for packaging are [here](https://github.com/linux-surface/linux-surface/tree/master/pkg/) and [here](https://github.com/linux-surface/linux-surface/tree/master/.github/workflows). Packages are built via GitHub actions and are pushed to the [releases](https://github.com/linux-surface/linux-surface/releases) page automatically. Our repository is just a fancy linking system that points to those (see [here](https://github.com/linux-surface/repo/)) and you can verify that the packages you get via the repository are bit for bit identical with what we have on the release page. Unless GitHub has been compromised in any way, I don't see any way that anyone, _including us maintainers_, can introduce any hidden spyware.

As I've said, I would be very much interested in any hard evidence. In particular, anything that helps finding the origin of that connection. None of the packages in our repos should do random internet connections (least of all the kernel), and if one does, that is indeed a serious issue.

**Comment by StollD** [comment] 2023-05-24 02:20
The answer is actually very easy: GitHub release artifacts are hosted on Fastly (tested by curl-ing one and looking at the headers), and your OS does a check for updated packages when you boot up your device.

**Comment by qzed** [comment] 2023-05-24 02:22
Whelp... I should have thought of that... So I guess try disabling auto-updates and see if the issue persists.

**Comment by qzed** [comment] 2023-05-30 09:44
Closing this as solved and as I'm not sure we'll ever get a response on this. I believe @StollD figured out what exactly happens and why. The update check is from your package manager/OS and not caused by any of our packages (or repos) directly. I'm sure there are ways to disable this check if you are concerned.

I do want to reiterate: If you detect anything out of the ordinary happening with our kernel or one of the packaged applications, please do  open an issue or notify us on Matrix/IRC. I do take these things seriously, but sadly I don't have the time to thoroughly vet all third-party dependencies (e.g. of our rust utilities)

**Closed by qzed** 2023-05-30 09:44 UTC
